### ISSUE TITLE
Plans for JSROOT as a library

### ISSUE THREAD

**Issue by riga** [linev/jsroot#1]
First of all, great project!
I really like the idea of browsing through root files with only JS.

At the moment, JSROOT is a single-page, stand-alone application. The question I want to ask is, whether you are planning to provide the core functionality as a JS library? I'm thinking of something like:

```html
<div id="myTreeDiv"></div>
...
<div id="myMainDiv"></div>
```

```javascript
var myJSRoot = new JSRoot({
    treeTarget: "#myTreeDiv",
    mainTarget: "#myMainDiv",
    otherOptions: ...
});

myJSRoot.open("relative/url/to/my/file.root");

// etc
```

This would be a pretty sweet feature as we are planning to integrate a ROOT-browsing tool into our [VISPA platform](https://vispa.physik.rwth-aachen.de/) that is designed to serve the needs of science, outreach and education.

**Comment by linev** [comment]
Hi,

Most of the work already done.

There is JSROOT.HierarchyPainter class which doing main job.

https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.js#L7226

In constructor one specifies element id, where tree structure will be displayed.

Method  JSROOT.HierarchyPainter.prototype.SetDisplay configures element for objects drawing.

https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.js#L8205

And there are methods to open file(s), display objects, access data from online server.

Up to now there were no other projects (beside my own) using these features,
therefore I did not document them well.

**Comment by riga** [comment]
Thanks for your reply!

I'm sure our users (~100 students, [CERN open data](http://opendata.cern.ch/) visitors)
would very appreciate seeing JSROOT and all its benefits on our platform.

I dived into your code, looks already very modular.
With the above example in mind, do you think this would be a major effort?

**Comment by linev** [comment]
I create simple example:

http://web-docs.gsi.de/~linev/js/dev/demo/example_h.htm

Probably it can be good idea to document JSROOT.HierarchyPainter interface.

**Comment by riga** [comment]
That's exactly what I was looking for.
Thanks!

**Comment by asseldonk** [comment]
There is one thing I do not understand. yet. How can I make the created histogram of your axample above responsive, meaning, how can I make it fit into a div that changes its size, when the browser's window size changes like in the example here:
https://root.cern.ch/js/dev/index.htm?file=../files/hsimple.root

**Comment by linev** [comment]
In my examples size of div elements are fixed and not changed when browser size is changing.
If your div layout changes with the browser, you could use function 

JSROOT.RegisterForResize()
https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.js#L8602

It accept either JSROOT.HierarchyPainter, used in example_h.htm like:
JSROOT.RegisterForResize(h)

or one could specify div identifier like from example.htm
JSROOT.RegisterForResize('object_draw');

**Comment by asseldonk** [comment]
thanks, that works fine.
