### ISSUE TITLE
require.js

### ISSUE THREAD

**Issue by asseldonk** [linev/jsroot#10]
In JSRootCore.js
```javascript
      // first configure all dependencies
      requirejs.config({
       baseUrl: dir,
       paths: {
          'd3'              : 'd3.v3.min',
          'helvetiker_bold' : 'helvetiker_bold.typeface',
          'jquery'          : 'jquery.min',
          'jquery-ui'       : 'jquery-ui.min',
          'touch-punch'     : 'touch-punch.min',
          'MathJax'         : 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_SVG&amp;delayStartupUntil=configured',
          'THREE'           : 'helvetiker_regular.typeface'
       },
```
 can you use baseUrl with 'context' like this:

````javascript
var reqOne = require.config({
  context: "version1",
  baseUrl: "version1"
});
```

(see: http://requirejs.org/docs/api.html#multiversion). When using only 'baseUrl' without 'context', it would overwrite and destroy any other configurations. With the 'context' option, jsroot would be more plugin-like.

**Comment by linev** [comment]
Hi

You mean I should provide code like:

     requirejs.config({
       context: dir,
       baseUrl: dir,
       paths: {

Or you prefer to use actual JSROOT version like:

     requirejs.config({
       context: "3.8",
       baseUrl: dir,
       paths: {

**Comment by asseldonk** [comment]
Hi,

a version is not necessary, you can use e.g.

```javascript
 requirejs.config({
   context: "jsroot",
   baseUrl: dir,
   paths: {
```

**Comment by linev** [comment]
Are you sure?
According to :
http://requirejs.org/docs/api.html#config-context
one should use unique identifier for context value. 
Let use version number. 
Is it ok with you?

**Comment by asseldonk** [comment]
You are right. A version number is better.

**Comment by linev** [comment]
I check new code with require.js - it does not work :(
I revert changes back.

**Comment by asseldonk** [comment]
But still the problem is that baseUrl is a global variable which might lead to errors when adding jsroot to an existing project or framework.
May be the usage of relative paths instead of baseUrl would be a solution. I will test it.

**Comment by linev** [comment]
I test usage of require.js with following page:

http://jsroot.gsi.de/dev/indexr.htm?nobrowser&file=../files/danilo6.root&item=canvas;1&opt=

You could try your variants based on it.

**Comment by asseldonk** [comment]
This seems to work for me:
https://github.com/asseldonk/jsroot

**Comment by linev** [comment]
I will see how your approach can be used.
You propose to avoid baseUrl at all and always use full path to the scripts.
I should verify that such modification does not affect existing code.

**Comment by linev** [comment]
Could you check latest code?
I use similar approach as yours, but keeping all kind of special configurations in JSRootCore.js
One benefit now - one could use minified versions of JSROOT scripts with require.js

**Comment by asseldonk** [comment]
I think 
```javascript
'rawinflate': dir + 'rawinflate' + ext
```
is missing in paths of the require config.

**Comment by linev** [comment]
Thanks. I add it (including minified version).

By the way, it was working? 
Seems to be require.js tries to load script from the same location.

**Comment by asseldonk** [comment]
Yes, it works. Thanks a lot.

**Comment by asseldonk** [comment]
I have another suggestion for require.js.
```javascript
      var paths = {
          'd3'                   : dir+'d3.v3.min',
          'jquery'               : dir+'jquery.min',
          'jquery-ui'            : dir+'jquery-ui.min',
          'touch-punch'          : dir+'touch-punch.min',
          'rawinflate'           : dir+'rawinflate'+ext,
          'MathJax'              : 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_SVG&amp;delayStartupUntil=configured',
          'THREE'                : dir+'three.min',
          'THREE_ALL'            : dir+'jquery.mousewheel'+ext,
          'helvetiker_regular'   : dir+'helvetiker_regular.typeface',
          'helvetiker_bold'      : dir+'helvetiker_bold.typeface',
          'JSRootCore'           : dir+'JSRootCore'+ext,
          'JSRootInterface'      : dir+'JSRootInterface'+ext,
          'JSRootIOEvolution'    : dir+'JSRootIOEvolution'+ext,
          'JSRootPainter'        : dir+'JSRootPainter'+ext,
          'JSRootPainter.more'   : dir+'JSRootPainter.more'+ext,
          'JSRootPainter.jquery' : dir+'JSRootPainter.jquery'+ext,
          'JSRoot3DPainter'      : dir+'JSRoot3DPainter'+ext
       };
       // check if modules are already loaded
       for (var module in paths) {
         if (requirejs.defined(module)) {
           delete paths[module];
         }
       }

      // first configure all dependencies
      requirejs.config({
       paths: paths,
       shim: {
         ...
'''

All the paths are saved in an object called paths. The for loops checks if a plugin is already loadad and removes it in this case from paths.

**Comment by linev** [comment]
I implement fix you provided.

**Comment by asseldonk** [comment]
Thanks a lot :-)
