### ISSUE TITLE
Support for TProfile2D

### ISSUE THREAD

**Issue by hcbeck** [linev/jsroot#100]
Hi, 

I am improving a web site which displays various plots (Histograms 1d, 2d, ...) using jsroot. Most of the plots are visible but some only have the camera icon and the question mark icon. I looked at the json files for the plots I get from the server. The common thing is that all (I looked at) missing plots have the class TProfile2D. I am wondering whether jsroot supports this class. Would it be possible for you to implement this if it is not supported now? That would be great because I can not change the classes of the graphs. 

Thanks in advance
Helge

**Comment by linev** [comment]
Hi Helge,

You are right - TProfile2D not yet supported.
After CHEP I will check that can be done.

Regards,
Sergey

**Comment by hcbeck** [comment]
Hi Sergey, 

thanks for the answer and for looking into it. 

Regards, 
Helge

**Comment by bellenot** [comment]
Hi,
This should not be very difficult. See for example:
https://bellenot.web.cern.ch/bellenot/Public/GitHub/?file=../Latest/files/profile2d.root&item=c1
(but there are still some issues - at least with contours)
Cheers, Bertrand.

**Comment by linev** [comment]
Bertrand, did you try contour plot of same object in ROOT?

**Comment by bellenot** [comment]
@linev Yes I did, and it works just fine

**Comment by linev** [comment]
Now TProfile2D supported in JSROOT.
[Here is an example](http://jsroot.gsi.de/dev/examples.htm#misc_profile2d)
Problem with 'cont' plot will be fixed separately.

**Comment by hcbeck** [comment]
Thank you, looks great. As soon it is released I will test it in my page. 

In the mean time I will open a new issue for a feature request. :)

**Comment by linev** [comment]
Latest code from 'dev' branch you always can test from http://jsroot.gsi.de/dev/ 
Or download package from http://jsroot.gsi.de/dev/JsRootDev.tar.gz

**Comment by linev** [comment]
Simple fix resolves issue with the contour plot.
Now it works with provided example:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/profile2d.root&item=c1;1/hprof2d&opt=cont

Actually, default contour plot in this particular profile is not very informative.
One should use cont2 or surf4 to really see the picture:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/profile2d.root&item=c1;1/hprof2d&opt=cont2
http://jsroot.gsi.de/dev/?nobrowser&file=../files/profile2d.root&item=c1;1/hprof2d&opt=surf4
