### ISSUE TITLE
Disentangling zooming enable/disable

### ISSUE THREAD

**Issue by hcbeck** [linev/jsroot#102]
Hi, 

I like both zooming features, drawing a rectangle and using the mouse wheel, but on pages with many plots I would like to be able to securely use scrolling to navigate the page and not get stuck in a plot. At the moment I therefore disabled zooming with the option provided. Would it be possible to have a option to only disable/enable the mouse wheel zooming and keeping the rectangle drawing? That would help people like me paying no attention to their mouse position a lot. 

Cheers,
Helge

**Comment by linev** [comment]
Hi Helge,

Now there are additional flags, which you can use:

         JSROOT.gStyle.ZoomMouse = false; // Zooming with the mouse events
         JSROOT.gStyle.ZoomWheel = false;  // Zooming with mouse wheel
         JSROOT.gStyle.ZoomTouch = false;  // Zooming with the touch devices

To disable zooming at all, use as before:

       JSROOT.gStyle.Zooming = false;

This should works properly with 2D graphics, with 3D (like lego) I need to check more.
You always can try latest 'dev' code with http://jsroot.gsi.de/dev/ 

Regards,
Sergey

**Comment by linev** [comment]
Now also show work in 3D mode

**Comment by hcbeck** [comment]
Hi Sergey, 
thanks for the fast response and implementation, exactly what I needed. 

Cheers,
Helge
