### ISSUE TITLE
Tool tip vanishing on right side of graphs next to an other graph

### ISSUE THREAD

**Issue by hcbeck** [linev/jsroot#103]
Hi, 

I noticed for neighbouring graphs (for example in your grid layout example http://jsroot.gsi.de/latest/api.htm#url_syntax_grid_layout) that the tool tip for the left graph is vanishing on the right side of the graph, probably under the other graph. For the bottom of the graph you shift the tool tip up to prevent this from happening there. If i remember correct this was a change in version 4.6. Perhaps you could do a similar thing for the right side of the graph?

Cheers,
Helge

**Comment by linev** [comment]
Hi Helge,

Now tooltip repositioned when too far right. 
Applyed for master and dev branch. 
See http://jsroot.gsi.de/dev/api.htm#url_syntax_grid_layout

Regards,
Sergey

**Comment by linev** [comment]
And thank for reporting this

**Comment by hcbeck** [comment]
Hi Sergey,  
nice solution

Cheers,
Helge
