### ISSUE TITLE
 TBufferJSON::ConvertToJSON producing wrong json???

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#105]
I am using ```TBufferJSON::ConvertToJSON(h);``` to produce json to and then show it on my web page. I am getting error in my web browser
```
TypeError: this.histo.getBinContent is not a function
```
I tried to show different histogram via
```
    JSROOT.OpenFile("https://jsroot.gsi.de/files/hsimple.root", function (file) {
      console.log(file);
      file.ReadObject("hpx;1", function (obj) {
        console.log(obj);
        JSROOT.draw("viewer", obj, "");
      });
    });
```
And i see that object produced by ```file.ReadObject``` has function ```getBinContent``` inside object.

Object produced by ```TBufferJSON::ConvertToJSON(h);``` doesn't have it. Can you give me hint?

I am using ROOT 6.06/08

**Comment by linev** [comment]
Hi Martin, 

When calling `TBufferJSON::ConvertToJSON()` method, only objects data are stored.
Straightforward way to work with JSON data in JSROOT is:

     JSROOT.NewHttpRequest("hpx.json", 'object', function(obj) {
         JSROOT.draw("drawing", obj, "hist");
      }).send();

Or working [web page](http://jsroot.gsi.de/dev/demo/example_json.htm)

If you get JSON string with other methods, you should parse it with command:

      var obj = JSROOT.parse(json_string);

If JSROOT recognize existing ROOT classes (like TH1), it will add several methods to it.

Regards,
Sergey

**Comment by mvala** [comment]
Thanks that works perfect
