### ISSUE TITLE
DateTime axis not supported ?

### ISSUE THREAD

**Issue by pionkaon** [linev/jsroot#106]
Hi - just discovered jsroot - it is AWESOME !!!!

I seem to have a problem getting it to display a time axis though :-( Not sure if it's my code or it's just not supported yet. Here is an example (in python)...

from array import array
from ROOT import TGraph
x = array('d', [1477008000., 1477267200., 1477353600., 1477440000., 1477526400.])
y = array('d', [1., 5., 3., 4., 4.])
g = TGraph(5, x, y)
g.SetTitle('Time;Date;Count')
g.Draw('AL*')
c1.Modified()
c1.Update()

This renders as you'd expect in ROOT and if I view it through a THttpServer it renders just fine in jsroot. However if I do this...

g.GetXaxis().SetTimeDisplay(1)
g.GetXaxis().SetTimeFormat('%Y%m%d')
g.GetXaxis().SetTimeOffset(0, 'gmt')
g.Draw('AL*')
c1.Modified()
c1.Update()

It renders fine in ROOT but in jsroot there is no X axis (and no graph line/points).

Did I do something wrong ?  If not is there any chance to implement the time axis ?

Thanks,

Euclid.

**Comment by linev** [comment]
Hi Euclid,

In principle, JSROOT supports  time axis
Like http://jsroot.gsi.de/latest/examples.htm#tcanvas_time
But it can be, that not all options are implemented.
Most probably,  SetTimeOffset(0, 'gmt') makes a problem.
I will check this on Monday.
  
Regards,
Sergey

**Comment by pionkaon** [comment]
You are right !  I looked at it again in more detail, the "local" option (default) is fine but "gmt" causes the problem, I'm guessing that is probably a simple fix.

Just wanted to say again how cool jsroot is. I'm working on some monitoring stuff (hence the time axes) and this makes it a million times easier (and more responsive) to distribute the graphs, and the interactive features allowing them to be explored will save a huge amount of web dev effort.

Thanks again !

**Comment by linev** [comment]
Hi Euclid,

This was minimal error in decoding of axis time offset.
Now will work like:
http://jsroot.gsi.de/dev/?json=../files/tmp/time.json.gz
I will include this fix also in next 4.7.1 release.

Regards,
Sergey

**Comment by pionkaon** [comment]
Thanks for fast turnaround !

I have another question - not related - but I'm not sure where to ask it - please let me know if there is a better place...

It's not clear to me from the docs how to load a root (or json) file from the local filesystem.

Am I right in thinking that it is not possible to load a file from the local filesystem using for example
https://root.cern.ch/js/latest/?file=../files/hsimple.root&item=hpx;1
? (I don't really want to set up a local THttpServer)

I have copied the JSROOT files into my webserver as ./static/js/jsroot/...
but I can't figure out how to use the scripts to load root or json files from the local filesystem.
Maybe there is an example in the tutorial or the examples that I didn't understand correctly - could you let me know how this should be done !?

Thanks, again.

**Comment by linev** [comment]
Hi,

Normally browser does not allow access local files.
There are different options for the different browsers to change such behavior.
For instance, for Chrome you can specify:

    [shell] /usr/bin/chromium  --allow-file-access-from-files --allow-access-from-files

But still only when your HTML page is on the file system, you could access ROOT files from the disk:

file:///home/user/jsroot/index.htm?file=file:///home/user/hsimple.root

This only possible with newest 'dev' branch.

Regards,
Sergey

**Comment by linev** [comment]
Normally I have opposite situation.
I develop my JavaScript code on the file system and test it with ROOT files from my web server. Doing like:

    file:///home/user/jsroot/index.htm?file=http://jsroot.gsi.de/files/hsimple.root

For that I need to specify:

     [shell] /usr/bin/chromium  --allow-access-from-files

**Comment by linev** [comment]
I close issue, fix now in 4.7.1 release
