### ISSUE TITLE
TBox does not show

### ISSUE THREAD

**Issue by pionkaon** [linev/jsroot#108]
Hi,
     I have a canvas with some graphs on and I have drawn some boxes (using TBox) adjacent to the graphs to show some parameters. When I save the canvas to a root file I can open the root file and the boxes render fine. When I open the root file in JSROOT the boxes do not render - could this be a bug ?

    I looked in JSRootCore.js and saw that TBox is referenced there - my Javascript isn't really good enough to investigate it further. Can you help ?

Thanks

**Comment by linev** [comment]
Can you provide ROOT file with such canvas?
In principle, TBox should be supported.

**Comment by pionkaon** [comment]
I tried to attach a root file here but it complained that it doesn't support files of that type. How can I get it to you ?

**Comment by linev** [comment]
Send me via email - S.Linev (at) gsi.de

**Comment by linev** [comment]
I see problem - you are using not a NDC coordinated for your boxes.
It is not yet supported - I will try to fix it

**Comment by pionkaon** [comment]
Ah ok - thank you. I also have an issue with a TMarker not being rendered - could it be the same thing ?

I'll send you another example root file...

**Comment by linev** [comment]
Issue with TBox drawing is fixed now.
Main problem was that box placed outside frame, but frame coordinates are used for drawing.

http://jsroot.gsi.de/dev/?file=../files/tmp/test.root&item=c1;1

TMarker simply not yet supported.
I will implement it soon

**Comment by pionkaon** [comment]
Thanks so much - much appreciated !

Where do I download the new version ?

(the link you posted doesn't show the boxes - is it using the previous version to render ?)

**Comment by linev** [comment]
Now also with TMarker:

http://jsroot.gsi.de/dev/?file=../files/tmp/testm.root&item=c1;1

Code in 'dev' branch, will be released very soon as 4.8 version

**Comment by linev** [comment]
> Where do I download the new version ?

Download link for dev version: http://jsroot.gsi.de/dev/JsRootDev.tar.gz

> the link you posted doesn't show the boxes - is it using the previous version to render ?)

Typical browser cache problem. You normally can clear it  with Ctrl+F5

**Comment by pionkaon** [comment]
Perfect !  Works great now. JSROOT is really awesome. Eventually I want to get to monitoring - can't wait !

**Comment by linev** [comment]
I guess, I can close issue
