### ISSUE TITLE
[question] Support for EVE

### ISSUE THREAD

**Issue by sashabaranov** [linev/jsroot#109]
Hello, 

I want to port SHiP experiment's [event display](https://github.com/ShipSoft/FairShip/blob/master/macro/eventDisplay.py) to root.js and wondering if it is possible.

The event display is based on [EVE](https://root.cern.ch/eve), does root.js plan to support it?

**Comment by linev** [comment]
Hi,

There is already geometry display in the JSROOT:

https://root.cern/js/latest/examples.htm#tgeo_eve

And it is also possible to superimpose geometry with tracks and hits:

https://root.cern/js/latest/examples.htm#tgeo_tracks+hits

There is browsing functionality (if you click on right-side arrow below the drawings).

But there is no application like EVE which organize them all together to be a full-functional event display. While here a lot of experiment-specific code should be implemented and till now nobody are willing to do such job. 

There is idea to make intermediate solution - create snapshot in the EVE, which can be displayed in JSROOT. But already this is not trivial - many relevant EVE classes cannot be stored in the ROOT files.

If you want to implement event display for SHiP experiment with JSROOT, we could discuss your requirements and evaluate if it would be doable or not.

Regards,
Sergey
