### ISSUE TITLE
Option to disable the hover popups

### ISSUE THREAD

**Issue by chenel** [linev/jsroot#112]
When there is more than one TH1 (etc.) drawn on the same canvas, the popup boxes with plot information often wind up covering the plots.  Since in my use case the overall shapes of the plots are more important than knowing the precise values of every point, can an option be introduced to disable them?

Thanks!

**Comment by linev** [comment]
Hi,

You can completely disable tooltips providing "tooltip=0" in URL string. Like:

https://root.cern/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=col&tooltip=0

Or programmatically:

    JSROOT.gStyle.Tooltip = 0;

Regards,
Sergey

**Comment by chenel** [comment]
Okay, thanks, that's interesting.  So, if I want to do it interactively, I need to write my own external controls into the page?  (And what if I have multiple canvases on the same page -- I guess this will affect them all simultaneously?)

**Comment by linev** [comment]
>  So, if I want to do it interactively, I need to write my own external controls into the page?

You can change global and local settings interactively.
If you activate context menu over empty space in the frame (or TFrame:: entry in list appeared after pressing ? mark), you can disable/enable tooltips for that particular frame.

In TCanvas context menu you can change global setting in JSROOT.gStyle.Tooltip.

> And what if I have multiple canvases on the same page -- I guess this will affect them all simultaneously?

Global value of JSROOT.gStyle.Tooltip used when object is drawn.

You propose to have it in draw options to be able configure it individually?

**Comment by chenel** [comment]
> You can change global and local settings interactively.
> If you activate context menu over empty space in the frame (or TFrame:: entry in list appeared after pressing ? mark), you can disable/enable tooltips for that particular frame.
This doesn't seem to work for me when I have multiple TH1s in the same canvas.  When I right-click anywhere in the blank space in the frame, I just get the context menu for one of the TH1s rather than the frame/pad (I show this in attached image, where the mouse cursor is at the upper-left of the context menu).  If, on the other hand, I click the "?" icon and select the "TCanvas" entry, I do see the "tooltips" option, but toggling it doesn't change anything.
![context_menu](https://cloud.githubusercontent.com/assets/15690871/21437353/642b993e-c851-11e6-9681-4a9ae84cc4c6.png)

**Comment by chenel** [comment]
> Global value of JSROOT.gStyle.Tooltip used when object is drawn.
> You propose to have it in draw options to be able configure it individually?

If it's easy, that would be helpful.  If it's not, then it's not a big deal.  I was mostly trying to understand the situation.

**Comment by linev** [comment]
You activating context menu associated with histogram.
As I can see, you have sub-pad in the canvas (therefore two sets of tool buttons on left and right sides).
Try to press ? mark on right side and select frame context menu.

**Comment by linev** [comment]
> If it's easy, that would be helpful. If it's not, then it's not a big deal.

It is doable. I will check. 
There are already some options (like grid or log settings), which can be changed via draw options, 
"notooltip" should be no problem

**Comment by linev** [comment]
Hi,

Implementing is very simple:

http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpx;1&opt=notooltip

But it will take some time before code appears in official release.
I currently significantly changing I/O part and all these changes requires a lot of testing.

Regards,
Sergey

**Comment by chenel** [comment]
> As I can see, you have sub-pad in the canvas (therefore two sets of tool buttons on left and right sides).
> Try to press ? mark on right side and select frame context menu.

Ah, that was the trick, that did it.  Though it would be nice if the right-click did it too. :)

> Implementing is very simple:
> http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpx;1&opt=notooltip
> But it will take some time before code appears in official release.
> I currently significantly changing I/O part and all these changes requires a lot of testing.

Great!  I'll look forward to when it drops in.

Thank you!

**Comment by linev** [comment]
Now in 5.0.0 version
