### ISSUE TITLE
Ability to call LorentzVector methods for TTree drawing

### ISSUE THREAD

**Issue by aminnj** [linev/jsroot#115]
Drawing the x,y,z,t components of a 4-vector is not as useful as pt, mass, eta, phi, so I am wondering if it would be easy/feasible to implement methods for TLorentzVectors like Pt(), M(), Eta(), Phi() that could be used like in a normal TBrowser. For example, opening the [WJets.root](http://uaf-8.t2.ucsd.edu/~namin/dump/jsroot/files/WJets.root) file with ROOT on the command line and opening a TBrowser gives me [these options](http://i.imgur.com/GVtyQJC.png), but jsroot 4.8.1 only lists [these options](http://i.imgur.com/6x5xAh9.png).

**Comment by linev** [comment]
Good point.
I will try to add such possibility in the dev branch, where much more functionality for TTree already provided.

**Comment by linev** [comment]
In dev version I add support of the object methods. Example is:

http://jsroot.gsi.de/dev/?file=../files/WJets.root&item=t&opt=lep1_p4.X()+lep1_p4.Y()

Actually, in dev branch I implement full support of TTree, including reading arbitrary branch data and
performing TTree::Draw - in this example draw expression is **lep1_p4.X()+lep1_p4.Y()**

There is one problem with TLorentzVectors classes - there are several coordinate systems and each with dozens of the methods. Could you implement them for all variants in JSROOT?
Example how it can be done you can find here:

https://github.com/linev/jsroot/blob/dev/scripts/JSRootMath.js#L650

Regards,
Sergey

**Comment by linev** [comment]
Possibility to call objects methods in TTree::Draw now available in version 5.0.0.
But for many ROOT classes one need to implement meaningful functions.

**Comment by aminnj** [comment]
Sorry to resurrect this. Completely lost track of this a long time ago. I have a few more functions (~6 lines in total) I can add. Shall I make a PR to the dev branch?
