### ISSUE TITLE
Enlarged TPad

### ISSUE THREAD

**Issue by DanielWielanek** [linev/jsroot#116]
Hi,
I think that it will be nice to have option of "enlarging pads" - like in  pages where you can click on image and see it "enlarged". Sometimes I draw TCanvas with many pads - and such option could be very useful.

**Comment by linev** [comment]
Interesting idea - I will try to implement it.

**Comment by linev** [comment]
Hi, 
I made a first try.
When sub-pad clicked outside the frame (and not on the histogram title), it should be enlarged. 
Like in this canvas: http://jsroot.gsi.de/dev/examples.htm#tcanvas_roofit
Is it that you meant?
Regards, Sergey

**Comment by DanielWielanek** [comment]
Hi,
I didn't expect such fast response  :) I also see 3 major problems here:
- it hard to enlarge this picture I have to click few times to find good place. In case of small pad marging - it might be a problem. (maybe adding button will be better?)
- I have no idea how return to previous view (only by refreshing page?)
- It should work in fact in two cases:
a) one big "div" with TCanvas with many small pads
b) few small divs with few small pads
I'm not JSROOT expert but can you handle both cases? Or just overwrite current div?
Originally I was thinking about something like here: http://fancybox.net/ - this is much more intuitive. However I suppose it much harder for implementation because histogram are not "static" like picture.

**Comment by linev** [comment]
´Hi,

> it hard to enlarge this picture I have to click few times to find good place. In case of small pad marging - it might be a problem. (maybe adding button will be better?)

Button can be created very easily. I just want to try functionality first.

> I have no idea how return to previous view (only by refreshing page?)

Just double click once again on the same area.

> It should work in fact in two cases:
> a) one big "div" with TCanvas with many small pads
> b) few small divs with few small pads

Yes, you are right. My solution works only inside canvas.

> Originally I was thinking about something like here: http://fancybox.net/ - this is much more intuitive. 

I agree. I will try to implement something like that - but it will take longer.

Regards,
Sergey

**Comment by linev** [comment]
Hi,

> Originally I was thinking about something like here: http://fancybox.net/ - this is much more intuitive.

I made a first try.
Probably, it is not so nice, but let display JSROOT drawing using complete window.
Now one could enlarge subpad or complete canvas. 
There are new tool button (circle) and command in context menu.

http://jsroot.gsi.de/dev/examples.htm#tcanvas_roofit
http://jsroot.gsi.de/dev/api.htm#url_syntax_grid_layout
http://jsroot.gsi.de/dev/api.htm#url_syntax_use_autozoom

Regards,
Sergey

**Comment by DanielWielanek** [comment]
Hi,
For me it's enough. I hope that  it will be in next version of JSROOT.

**Comment by linev** [comment]
Now in 5.0.0 release
