### ISSUE TITLE
ROOT file loading stops working since 5.0

### ISSUE THREAD

**Issue by chenel** [linev/jsroot#119]
Hi,

Since the 5.0 release, I'm no longer able to load histograms (and draw them) from ROOT file I/O.  When opening files that used to (and still) work with 4.8.2, I see many warnings like this in my browser console:

```
Not found streamer for TPad ver 11 checksum undefined TPad$ver11  JSRootIOEvolution.min.js:1:39068
Missmatch in TPad bytecount expected = 461729  got = 0  JSRootIOEvolution.min.js:1:5481
Not found streamer for TAttCanvas ver 1 checksum undefined TAttCanvas$ver1  JSRootIOEvolution.min.js:1:39068
Missmatch in TAttCanvas bytecount expected = 24  got = 0

```
and the object that's returned by the `ReadObject()` call I use (see below) is now `null`.

Do I need to change something in my load syntax?  The tutorial syntax still seems to be the same as what I'm using:
```
JSROOT.OpenFile(rootfileName, function(obj) { obj.ReadObject("canvas", function(c) { draw_rootfile(c, divId); }); })
```
where `canvas` is the name of the TH1 inside the ROOT file, and `draw_rootfile()` just calls `JSROOT.draw()` on the canvas loaded from the ROOT file if successful, and shows an error otherwise.

Thanks!

**Comment by linev** [comment]
Hi,

Can you provide file where problem appears?
I was expecting that basic I/O works as before - at least all my testcases are working.

https://root.cern.ch/js/latest/examples.htm#tcanvas_roofit

Regards,
Sergey

**Comment by chenel** [comment]
Apparently GitHub won't let me attach a ROOT file to the message, but one of the many that I expected to be able to open in my script is here:

http://nusoft.fnal.gov/nova/users/jwolcott/validation/new_test/test_dataset1/dir1/h_var{all_overlay}{group=Normalization,cat=raw}.root

Thanks!

**Comment by linev** [comment]
Hi,

I cannot use file directly from your web server (Access-Control-Allow-Origin header is not set). 
But after I download it, I can display canvas without problem:

http://jsroot.gsi.de/5.0.2/?file=http://jsroot.gsi.de/files/tmp/h_var.root&item=canvas

Also file can be used in custom web-page:

http://jsroot.gsi.de/files/tmp/h_var.htm

    <script src="/5.0.2/scripts/JSRootCore.min.js" type="text/javascript"></script>

    <script type='text/javascript'>
      JSROOT.OpenFile("h_var.root", function(file) {
        file.ReadObject("canvas;1", function(obj) {
           JSROOT.draw("drawing", obj);
        });
     });
     </script>

Can it happen, that your file changes during the request? This can be solved by adding "+" sign to the file name like "h_var.root+". In this case JSROOT loads complete file with single HTTP request -  should be ok in your case.

Or may be server reacts wrong when JSROOT adds parameters to file URL.
When file requested, URL looks like "http://jsroot.gsi.de/files/tmp/h_var.root?stamp=123456789". 
This is done to overcome typical browser cache problems. 

Regards,
Sergey

**Comment by linev** [comment]
You can enable CORS requests in your browser with [CORS Everywhere](https://addons.mozilla.org/de/firefox/addon/cors-everywhere/) plugin for the Firefox.

In this case one can address your file [directly via URL](http://jsroot.gsi.de/dev/?item=canvas&file=%27http://nusoft.fnal.gov/nova/users/jwolcott/validation/new_test/test_dataset1/dir1/h_var{all_overlay}{group=Normalization,cat=raw}.root%27) or in the [HTML page](http://jsroot.gsi.de/files/tmp/h_cors.htm)

Here I use __dev__ version, while only there I implement quotes handling in the URL.

**Comment by chenel** [comment]
What I don't understand about all of this is why it would work with 4.8.2 --- because it still does! --- and not with 5.0.  Do you have any thoughts about that?

**Comment by linev** [comment]
There are many changes in JSROOT 5.0 compare to 4.8 - especially in I/O part.

But I cannot reproduce your problem :(
Is it exactly the same file?

That OS / browser your are using? May be it is IE9?
I decide to skip support of older IE - only IE11 is really works, probably IE10

**Comment by chenel** [comment]
Yep, exactly the same file,  In fact it happens with every .ROOT file I try -- works fine with 4.8.2, has the problem I described above with 5.0.  I've been testing with Firefox 51 on Linux, but other users using various browsers on Mac have had the same problem.

**Comment by linev** [comment]
> with Firefox 51 on Linux,

This is that I use all the time. And file itself is ok. 

    JSROOT.OpenFile(rootfileName, function(obj) { 
         obj.ReadObject("canvas", function(c) { 
            draw_rootfile(c, divId); 
        }); 
     })
 
Is it exactly the code you are using?

     Not found streamer for TPad ver 11 checksum undefined TPad$ver11 JSRootIOEvolution.min.js:1:39068

This is strange - TPad version 11 exists in the list of streamer infos.

http://jsroot.gsi.de/dev/?file=http://jsroot.gsi.de/files/tmp/h_var.root&item=StreamerInfo

Can you try to replace "canvas" with "StreamerInfo" in your code?
 Do you see "TPad;11" in the list?

**Comment by linev** [comment]
Also can you check type of rootfileName. Just add in the code:

   console.log(typeof rootfileName)

It should return string, otherwise JSROOT 5 tries to open it as local file.

**Comment by linev** [comment]
Finally, can you reduce your problem to minimal web-page (like http://jsroot.gsi.de/files/tmp/h_cors.htm), which reproduce the problem? 
Just copy it to your server and try to open - it should work without disabling CORS security checks.

**Comment by chenel** [comment]
Hmm, error message has changed since the last time I tried this.  Now in the (Firefox) browser console:

```
TypeError: l is null[Learn More]  JSRootIOEvolution.min.js:1:3279
	b.R__unzip http://root.cern.ch/js/latest/scripts/JSRootIOEvolution.min.js:1:3279
	b.TFile.prototype.ReadObjBuffer/< http://root.cern.ch/js/latest/scripts/JSRootIOEvolution.min.js:1:21174
	b.TFile.prototype.ReadBuffer/l http://root.cern.ch/js/latest/scripts/JSRootIOEvolution.min.js:1:18061
	l http://root.cern.ch/js/latest/scripts/JSRootCore.min.js:1:11089
	b.NewHttpRequest/j.onreadystatechange http://root.cern.ch/js/latest/scripts/JSRootCore.min.js:1:11394
```

Also:

>```JSROOT.OpenFile(rootfileName, function(obj) { 
     obj.ReadObject("canvas", function(c) { 
        draw_rootfile(c, divId); 
    }); 
 })```
> Is it exactly the code you are using?

Yep, I copied & pasted.

> Can you try to replace "canvas" with "StreamerInfo" in your code?

Changing `"canvas"` to `"StreamerInfo"` didn't change anything.

> Also can you check type of rootfileName. Just add in the code:
> ``` console.log(typeof rootfileName)```
> It should return string, otherwise JSROOT 5 tries to open it as local file.

Apparently `rootfileName` is of type `string`, as expected.

> Do you see "TPad;11" in the list?

I'm not sure which list you mean?

**Comment by chenel** [comment]
> Finally, can you reduce your problem to minimal web-page (like http://jsroot.gsi.de/files/tmp/h_cors.htm), which reproduce the problem?

I'll try this and report back.

**Comment by linev** [comment]
Can you load not minified version of scripts? It will be easier to debug the problem.

**Comment by chenel** [comment]
Ah, sure, sorry.  Error is:

```
TypeError: arr is null[Learn More]  JSRootIOEvolution.js:144:11
	JSROOT.R__unzip http://root.cern.ch/js/latest/scripts/JSRootIOEvolution.js:144:11
	JSROOT.TFile.prototype.ReadObjBuffer/< http://root.cern.ch/js/latest/scripts/JSRootIOEvolution.js:1250:26
	JSROOT.TFile.prototype.ReadBuffer/read_callback http://root.cern.ch/js/latest/scripts/JSRootIOEvolution.js:1053:20
	callback http://root.cern.ch/js/latest/scripts/JSRootCore.js:690:51
	JSROOT.NewHttpRequest/xhr.onreadystatechange http://root.cern.ch/js/latest/scripts/JSRootCore.js:706:23
```

**Comment by linev** [comment]
Hi,

There is more information, but still not clear a reason for the error.
I made small fix. Can you try to use JSROOT version from "https://jsroot.gsi.de/dev/"

**Comment by linev** [comment]
I am not sure that my patch will help - it is just correct exit when reading of object buffer fails.

**Comment by linev** [comment]
One more question - can you check that is value of JSROOT.IO.Mode variable before opening file and before requesting object?

**Comment by chenel** [comment]
I've copied your sample page into my web server area (http://nusoft.fnal.gov/nova/users/jwolcott/test/).  Interestingly, if I use the CERN JSROOT, I get the errors above; if on the other hand I use jsroot.gsi.de/dev, nothing seems to happen at all.

**Comment by chenel** [comment]
> can you check that is value of JSROOT.IO.Mode variable before opening file and before requesting object?

If I insert a console line to write this out, I get:
``` TypeError: JSROOT.IO is undefined ```

**Comment by linev** [comment]
> If I insert a console line to write this out, I get:
>  TypeError: JSROOT.IO is undefined

This I can understand.
Before opening file IO functionality is not yet loaded.

> Interestingly, if I use the CERN JSROOT, I get the errors above; if on the other hand I use jsroot.gsi.de/dev, nothing seems to happen at all.

I add few more checks, which are not yet updated on root.cern.ch site.
Now in case of failure it just return null object.

> I've copied your sample page into my web server area

This is very good - I can reproduce and debug problem.
I see strange replies from your server - seems to be it returns all data in gzip form.
Normally browser unpack it behind the scene.
On Monday I can give you more information.
Can you keep test page as is?

If you want, you can try one thing - add "+" sign at the end of the file name.  like:

     var filename = "http://nusoft.fnal.gov/nova/users/jwolcott/validation/new_test/test_dataset1/dir1/h_var{all_overlay}{group=Normalization,cat=raw}.root+";

This may help, but please return then back to original state - on Monday I want to debug and understand problem.
Most probably, it is special configuration of your server.

**Comment by linev** [comment]
> I've copied your sample page into my web server area (http://nusoft.fnal.gov/nova/users/jwolcott/test/). 

By the way, it works fine with IE.

Seems to be, problem really with gzip encoding on server side.
Normally browser should unpack it automatically, but FireFox and Chrome fail. 
Only IE does it properly.
I will check that on Monday

**Comment by linev** [comment]
Seems to be, I fix a problem.
It is due to automatic gzip compression on server side.
ROOT data already gzipped, therefore server produces response larger than original data.
In new JSROOT I detect such situation and generate error. 

There are extreme situations, when some HTTP servers do not support partial data request and after simple request for small portion of data tries to return complete file content which can be many GB. Therefore JSROOT breaks when see more data in response as expected. 

Probably, I need to add some log output to clearly identify error.

Thanks for reporting the problem.
I will provide bug fix release very soon.

**Comment by mvala** [comment]
Hi, was it fixed in https://jsroot.gsi.de/dev/? Because i am getting gzip error there. When i use 5.0.2 in https://root.cern.ch/js/latest it is fine

**Comment by linev** [comment]
Error should be fixed in dev branch and in https://jsroot.gsi.de/dev/

> Because i am getting gzip error there. 

Where you get the error?

**Comment by mvala** [comment]
Just doing
```
    let filename = "https://root.cern.ch/js/files/hsimple.root";
    JSROOT.OpenFile(filename, function (file) {
```
and i get
```
error_handler.js:54 EXCEPTION: Cannot read property 'arr_inflate' of undefined
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.544.ZoneDelegate.handleError @ zone.js:246
webpackJsonp.544.Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.544.ZoneDelegate.handleError @ zone.js:246
webpackJsonp.544.Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:60 TypeError: Cannot read property 'arr_inflate' of undefined
    at Object.JSROOT.R__unzip (JSRootIOEvolution.js:180)
    at JSRootIOEvolution.js:1156
    at XMLHttpRequest.read_callback (JSRootIOEvolution.js:969)
    at callback (JSRootCore.js:681)
    at XMLHttpRequest.xhr.onreadystatechange (JSRootCore.js:731)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (zone.js:1039)
    at ZoneDelegate.webpackJsonp.544.ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:264)
    at ZoneDelegate.webpackJsonp.544.ZoneDelegate.invokeTask (zone.js:274)
    at Zone.webpackJsonp.544.Zone.runTask (zone.js:151)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:345)
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.544.ZoneDelegate.handleError @ zone.js:246
webpackJsonp.544.Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
Subscriber.js:227 Uncaught TypeError: Cannot read property 'arr_inflate' of undefined
    at Object.JSROOT.R__unzip (JSRootIOEvolution.js:180)
    at JSRootIOEvolution.js:1156
    at XMLHttpRequest.read_callback (JSRootIOEvolution.js:969)
    at callback (JSRootCore.js:681)
    at XMLHttpRequest.xhr.onreadystatechange (JSRootCore.js:731)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (zone.js:1039)
    at ZoneDelegate.webpackJsonp.544.ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:264)
    at ZoneDelegate.webpackJsonp.544.ZoneDelegate.invokeTask (zone.js:274)
    at Zone.webpackJsonp.544.Zone.runTask (zone.js:151)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:345)
JSROOT.R__unzip @ JSRootIOEvolution.js:180
(anonymous) @ JSRootIOEvolution.js:1156
read_callback @ JSRootIOEvolution.js:969
callback @ JSRootCore.js:681
xhr.onreadystatechange @ JSRootCore.js:731
wrapFn @ zone.js:1039
webpackJsonp.544.ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:264
webpackJsonp.544.ZoneDelegate.invokeTask @ zone.js:274
webpackJsonp.544.Zone.runTask @ zone.js:151
ZoneTask.invoke @ zone.js:345
```

**Comment by linev** [comment]
Hi, 

Looks like rawinflate.min.js script is not loaded for you.
Do you load JSRootIOEvolution.js script yourself? 
In that case you should add rawinflate.min.js script.

Regards,
Sergey

**Comment by mvala** [comment]
Yes this works, but strange thing is that i don't have to load it via https://root.cern.ch/js/latest

**Comment by mvala** [comment]
And yes, i am loading it by myself

**Comment by linev** [comment]
I change implementation of JSROOT.OpenFile()
Actual implementation now in JSRootIOEvolution.js and in such case rawinflate.min.js should be already loaded.
I can add protection in the code, but normally both scripts should be loaded together.

**Comment by mvala** [comment]
It is fine, from my side

**Comment by linev** [comment]
This and few other fixes now available in JSROOT 5.0.3 bugfix release

http://nusoft.fnal.gov/nova/users/jwolcott/test/

Now should also work with https://root.cern/js/latest/

**Comment by chenel** [comment]
Agreed, this solves my problem.  Thanks for hunting it down!
(sorry it took me so long to respond, for some reason GitHub hasn't been sending me emails and I forgot to check this page.)

**Comment by linev** [comment]
No problem - I want to be sure that provided solution helps.
