### ISSUE TITLE
No instructions for how to use with bower

### ISSUE THREAD

**Issue by nasfarley88** [linev/jsroot#120]
I see that there is a `bower.json` in this repo, but no instructions for how to install using bower.

Could some be included in the README?

**Comment by linev** [comment]
There is example, where jsroot installed via bower:

https://github.com/linev/jsroot-example

> Could some be included in the README?
I will do it.

**Comment by nasfarley88** [comment]
Sounds good.

Those instructions do not work on my setup, but it might be my fault. I'll raise a new issue if I think it is a bug.

**Comment by linev** [comment]
> Those instructions do not work on my setup, but it might be my fault.

Did you try to clone jsroot-example and run "npm start"?
I test it shortly after last 5.0.0 release - it was working.

**Comment by nasfarley88** [comment]
We use a gulpfile, which takes an array of values for javascript filenames, so passing an argument via URL is not so trivial. Here is the file we load using gulp: 

```
$ cat vendor.base.json 
[
  "bower_components/jquery/dist/jquery.js",
  "bower_components/lodash-compat/lodash.js",
  "bower_components/angular/angular.js",
  "bower_components/angular-route/angular-route.js",
  "bower_components/angular-cookies/angular-cookies.js",
  "bower_components/angular-animate/angular-animate.js",
  "bower_components/angular-ui-router/release/angular-ui-router.js",
  "bower_components/ngstorage/ngStorage.js",
  "bower_components/angular-ui-utils/ui-utils.js",
  "bower_components/angular-sanitize/angular-sanitize.js",
  "bower_components/angular-resource/angular-resource.js",
  "bower_components/angular-translate/angular-translate.js",
  "bower_components/angular-translate-loader-url/angular-translate-loader-url.js",
  "bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js",
  "bower_components/angular-translate-storage-local/angular-translate-storage-local.js",
  "bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js",
  "bower_components/oclazyload/dist/ocLazyLoad.js",
  "bower_components/angular-bootstrap/ui-bootstrap-tpls.js",
  "bower_components/angular-loading-bar/build/loading-bar.js",
  "bower_components/restangular/dist/restangular.js",
  "bower_components/checklist-model/checklist-model.js",
  "bower_components/jsroot/scripts/JSRootCore.js"
]
```

I'm not yet sure whether URL parameters can be passed using gulp. However, if bower was the default (so no URL parameters needed to be passed), it would save me a lot of time. 

If this is something you'd like to discuss, I'd be happy to open a new issue about it.

**Comment by linev** [comment]
> I'm not yet sure whether URL parameters can be passed using gulp. 

Can you check this? Script name should be:
"bower_components/jsroot/scripts/JSRootCore.js?bower"

> However, if bower was the default (so no URL parameters needed to be passed), it would save me a lot of time.

JSROOT used very rarely via bower and main (default) use-case is definitely not a bower.
One could use some semantics  - like if path name contains "bower_components/jsroot/scripts", bower support will be automatically enabled

**Comment by nasfarley88** [comment]
I tried that, it didn't work: 
```
lhcbpr2fe_1     | [12:33:55] ✗ FAIL: Missing 1 expected files: bower_components/jsroot/scripts/JSRootCore.js?bower
```

Automatic support would work well.

Is there a reason bower/a package manager is not the default use case? Many other js libraries use multiple package managers without problems, although I'm not sure how they do it.

**Comment by linev** [comment]
>  Many other js libraries use multiple package managers without problems

JSROOT supports require.js and bower. One can add some more (if necessary).

> Is there a reason bower/a package manager is not the default use case?

Main reason - keep dependencies minimal.
At the moment default use-case - graphical interface for THttpServer in ROOT. 
Here neither bower nor require.js are used. 

I propose intermediate solution - enable bower support when "bower_components/jsroot/scripts" appears  in the scripts path. Are you agree?

**Comment by nasfarley88** [comment]
Yes, I think that will work well for now.

**Comment by linev** [comment]
Now in 5.1.0 release
