### ISSUE TITLE
Togle 3D mode doesn't work

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#121]
I wanted to try "Togle 3D mode" and it shows empty (white cancas). One can reproduce it here
https://root.cern.ch/js/latest/api.htm#custom_html_read_root_file

It is working here:
https://root.cern.ch/js/latest/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=COLZ

**Comment by linev** [comment]
Hi Martin,

Thank you for reporting the problem.
It appears in IE and Chrome/Opera, but most of my testing I did with Firefox.
Now should work:

https://jsroot.gsi.de/dev/api.htm#custom_html_read_root_file

Regards,
Sergey

**Comment by mvala** [comment]
Thanks. it is fine now

**Comment by mvala** [comment]
In Fedora 25 (in firefox) i am just getting following warning. But this is because fedora is using by default Wayland instead of Xorg
```
14:10:21.368 THREE.WebGLShader: gl.getShaderInfoLog() fragment 0:2(12): warning: extension `GL_ARB_gpu_shader5' unsupported in fragment shader
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshBasicMaterial
4: #define GAMMA_FACTOR 2
5: #define DOUBLE_SIDED
6: #define NUM_CLIPPING_PLANES 0
7: #define UNION_CLIPPING_PLANES 0
8: uniform mat4 viewMatrix;
9: uniform vec3 cameraPosition;
10: #define TONE_MAPPING
11: #define saturate(a) clamp( a, 0.0, 1.0 )
12: uniform float toneMappingExposure;
13: uniform float toneMappingWhitePoint;
14: vec3 LinearToneMapping( vec3 color ) {
15: 	return toneMappingExposure * color;
16: }
17: vec3 ReinhardToneMapping( vec3 color ) {
18: 	color *= toneMappingExposure;
19: 	return saturate( color / ( vec3( 1.0 ) + color ) );
20: }
21: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
22: vec3 Uncharted2ToneMapping( vec3 color ) {
23: 	color *= toneMappingExposure;
24: 	return saturate( Uncharted2Helper( color ) / Uncharted2Helper( vec3( toneMappingWhitePoint ) ) )[…] 1 three.min.js:59:253
```

**Comment by linev** [comment]
This is due to new three.js library v84.
It depends from your graphic card driver.
For the moment just ignore this warning.
