### ISSUE TITLE
Drawing two objects on the same page causes one to be made invisible (as of v5.1.0)

### ISSUE THREAD

**Issue by nasfarley88** [linev/jsroot#123]
I have a case where I draw two histograms on the same page in quick succession and when I upgraded JSROOT to version 5.1.0 (from 5.0.3), both histograms are 'plotted' (i.e. they show up in the Chrome Developer Tools inspection) but one is `visible="visible"` and the other is `visibility="hidden"`.

If it is important, the plots were simple TH1 plots, generated in ROOT beforehand.

**Comment by linev** [comment]
> I have a case where I draw two histograms on the same page

On the same page or in the same div, using "same" draw option?

**Comment by nasfarley88** [comment]
On the same page using different divs (with different ids).

**Comment by linev** [comment]
Simple example works for me:

http://jsroot.gsi.de/files/tmp/read2hist.htm

Visibility attribute can be set to "hidden", when JSROOT fails to correctly define geometry of your div.
Can you provide clear width and height parameter in pixels (like on demo page)?

**Comment by nasfarley88** [comment]
I already provide width and height in that way but the plot does not respect it. The plots are also both inside a table. The space for the plot is reserved it's just not visible (as picture, red highlight added by hand)

![image](https://cloud.githubusercontent.com/assets/1312119/23470677/f4a1a1ba-fe9e-11e6-81da-99ec39f0d460.png) 

Is it possible that the change in table width/height as one is plotted disrupts the other? What would you recommend to avoid this?

**Comment by linev** [comment]
If you do not plot histograms, are divs on there place?
It could be that your table layout moves div to some other position.

Can you provide your HTML code, that I can reproduce the problem?

**Comment by nasfarley88** [comment]
The HTML is dynamically generated within an angularJS application, but the HTML is roughly something like:

```
<table>
<tr>
<td>
<div id="plotid3fhre0a9fh3ef0ajwrefbj39fjnaksd"></div>
</td>
<td>
<div id="plotid23fj9ar0ujf9reaufajfewf0aw94efh"></div>
</td>
</tr>
<table>
```

where the div ids are constucted from javascript as 

```
# the div element
element.id = "plotid"+randomString(64)
```
where `randomString` is a function which generates a string of length `64` with random letters/numbers.

Where is the code reponsible for deciding to hide/not hide in JSROOT? I've been looking around but I'm not an experienced JS dev so I'm not sure where this would be done.

**Comment by linev** [comment]
I will check tomorrow.

**Comment by linev** [comment]
I change layout on test HTML page - it also working with table:

http://jsroot.gsi.de/files/tmp/read2hist.htm

I check the code. The only condition when "visibility" attribute set to "hidden" - 
when JSROOT detects available div space and either width or height is 0 or negative.
You can check yourself if you want - code is here:

https://github.com/linev/jsroot/blob/5.1.0/scripts/JSRootPainter.js#L3973-L4094

Can you try to use my dev version - https://jsroot.gsi.de/dev/ or just dev branch?
I add several warnings which could give us a hint for the problem

**Comment by nasfarley88** [comment]
Ah, that makes perfect sense. Before the plots are drawn, the table has 0 height, which is probably passed on to the div. When the second plot is drawn, the table's height now matches the first plot (100 px as per https://github.com/linev/jsroot/blob/5.1.0/scripts/JSRootPainter.js#L4067). 

Is there a reason the plot is hidden at 0 width/height and then changed size? If not, then possibly this could be changed to just resizing the plot?

I'll give the dev version a try tomorrow to confirm this.

**Comment by linev** [comment]
> Is there a reason the plot is hidden at 0 width/height and then changed size?

There are many reasons why div geometry can have zero height or width.
For instance, when display=none is set. 
Before I had many problems due to that. 

Normally size of div is not changed - with one exception. 
When height===0 and width>0, I set meaningful div height.
This is due to "collapsible" layout. Probably I will improve this.

At the best you should provide div geometry before start drawing objects.
This is the only reliable way of work.

**Comment by nasfarley88** [comment]
That makes sense. I think a console.log message when the div is resized saying divs should have non-zero width and height would be enough for future developers to understand what is happening.

**Comment by linev** [comment]
> I think a console.log message when the div is resized saying divs should have non-zero width and height would be enough for future developers to understand what is happening.

Probably, I only add warning to the console.

In my mind, it is not good idea to change page layout that way.
At least, not by default.
Current implementation is sub-optimal. It was remaining from very early JSROOT code.
Probably, now is good chance to change it.

**Comment by linev** [comment]
I made several adjustments.

First of all, there is warning when geometry for the div element not specified.
Second, one can allow that JSROOT adjust div sizes. 
For that one should add can_resize attribute.

    <table>
    <tr>
    <td>
    <div id="plotid3fhre0a9fh3ef0ajwrefbj39fjnaksd" can_resize="true"></div>
    </td>
    <td>
    <div id="plotid23fj9ar0ujf9reaufajfewf0aw94efh" can_resize="true"></div>
    </td>
    </tr>
    </table>

In such case canvas size will be used (which is by default 500x300).

**Comment by linev** [comment]
This is example with can_resize attribute:

https://jsfiddle.net/Ls5nvtfw/

**Comment by nasfarley88** [comment]
I'm satisfied that this issue has been addressed. Shall we close @linev?

**Comment by linev** [comment]
Fine
