### ISSUE TITLE
Flex layout and rotating 3d object

### ISSUE THREAD

**Issue by asseldonk** [linev/jsroot#22]
When I use the flex layout and rotate a 3d object, the object rotates fine but also the flex box moves around.

**Comment by linev** [comment]
Thanks for the info, I will check it

**Comment by asseldonk** [comment]
You can see the effect e.g. in the glbox example.

**Comment by linev** [comment]
Now should be fixed. See result:

http://jsroot.gsi.de/dev/?layout=flex&file=../files/glbox.root&item=h31;1

There is still problem with resize of 3D drawings, but I will address this issue later

**Comment by asseldonk** [comment]
Great, thanks.
JSROOT makes great progress, I really enjoy that!
