### ISSUE TITLE
d3 error

### ISSUE THREAD

**Issue by asseldonk** [linev/jsroot#25]
Hi,

I receive a d3 error:

Error: Invalid value for <path> attribute d="null"

when running c46 in the graph.root example.
Nevertheless, a graph is shown (should it be a polar graph? i see an euclidean plane), so maybe it is not a critical issue.

**Comment by linev** [comment]
Hi,
This was because of TGraphPolargram class.
I add simple protection against it.
But as you could see TGraphPolar drawing not yet supported.
Thanks for reporting the problem.
Regards,
Sergey

**Comment by asseldonk** [comment]
Does the sqroot graph of the fillrandom.root file work for you with require.js? I receive a require error:
Uncaught ReferenceError: JSROOT is not defined

**Comment by linev** [comment]
Yes, I see an error with require.js. Will investigate it....

**Comment by linev** [comment]
When loading modules with require.js, no global variables like JSROOT or JSROOT.Math are defined.
Therefore I need to keep them locally to use in TF1::Eval expression.
Should work now.
Thanks for reporting it.

**Comment by asseldonk** [comment]
Great, thanks.
