### ISSUE TITLE
hover in 3d

### ISSUE THREAD

**Issue by asseldonk** [linev/jsroot#26]
Hi,
I think the hover effect (highlighting of elements on mouseover) doesn't work anymore in 3D graphs.
Furthermore, I receive the same number of toolbars as graphs are shown in a canvas.

**Comment by linev** [comment]
Hi,

> I think the hover effect (highlighting of elements on mouseover) doesn't work anymore in 3D graph

Depending from rendering time, I enabling or disabling this feature.
This typically happens when browser does not support webgl. 
At the moment time limit is 1.4s. You could check in your browser console - 
it shown there as "First render tm".

>  I receive the same number of toolbars as graphs are shown in a canvas.
Could be - we not yet finish with toolbar implementation. 
I saw problem with other canvas and will fix it soon.

Regards,
Sergey

**Comment by asseldonk** [comment]
For me it does not work, although tm < 1.4s (webgl is supported).

**Comment by linev** [comment]
> For me it does not work, although tm < 1.4s (webgl is supported).
Do you mean TGeo drawings or TH2/TH3?

**Comment by asseldonk** [comment]
TH3, e.g. hsimple py vs px

**Comment by linev** [comment]
You mean this:
http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=lego

It works fine for both webgl / no-webgl cases.
That browser/OS do you have?

**Comment by asseldonk** [comment]
> You mean this:
http://jsroot.gsi.de/dev/?nobrowser&file=../files/hsimple.root&item=hpxpy;1&opt=lego
Yes

I use Chrome on OSX (10.11.3)

**Comment by linev** [comment]
I use Chrome on Windows (with webgl) and Linux (no webgl).
Both are ok. 
Did you clean browser cache?

**Comment by asseldonk** [comment]
Yes, cache is cleared.
I just tried firefox, but it is too slow. Can you tell me the line in which the 1.4s is set? Than I can set it to higher values and test firefox again.

**Comment by linev** [comment]
Here:
https://github.com/linev/jsroot/blob/master/scripts/JSRoot3DPainter.js#L75

Actually it is 1.2 sec.

**Comment by asseldonk** [comment]
Ah, ok. My Chrome was just a bit above 1.2s. When I set it to higher values, it works. 
Thanks a lot.

**Comment by linev** [comment]
Actually, I could increase this limit. 

This was adjusted for my testing - my Firefox without webgl is slower (and disables this feature),
when my Chrome is typically faster and enables it. I could set it to 2 sec.
