### ISSUE TITLE
Disappearing parts of graph

### ISSUE THREAD

**Issue by asseldonk** [linev/jsroot#27]
Hi,
I have a strange behaviour when using the flex layout. When I resize a box and zoom in afterwards, parts of the graph disappear (lower y and upper x range).

Best regards
Daniel

![screen shot 2016-02-17 at 14 56 08](https://cloud.githubusercontent.com/assets/6368986/13111565/c61fb968-d586-11e5-98b7-92c4d90dbbb4.png)

**Comment by linev** [comment]
Thanks for the info.
I saw such effect once (with default layout), but was not able to reproduce it.
I try to check it again.

**Comment by linev** [comment]
Hopefully fixed.
Please try from repository or from:
http://jsroot.gsi.de/dev/

**Comment by asseldonk** [comment]
Yes, it works. Thanks a lot!
Is it possible to resize/readjust the fonts (e.g. graph titles, entries in stat box) after resizing an svg like it is done after zooming? The problem is that after resizing a box, fonts might be shown distorted.

**Comment by linev** [comment]
> Is it possible to resize/readjust the fonts (e.g. graph titles, entries in stat box) after resizing an svg like it is done after zooming? The problem is that after resizing a box, fonts might be shown distorted.

Somehow it is intended behavior. 
After small resize of canvas I do not redraw SVG - it as automatically re-scaled by browser.
Only when changes are significant (more than 2 times), redrawing is forced.
I could make such factor smaller (may be 1.7 or 1.5)?
If you like, you could play yourself - code is here:

https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.js#L3533-L3538

**Comment by asseldonk** [comment]
I tried some numbers and I guess 1.5 might be good.
