### ISSUE TITLE
Palette does not disappear

### ISSUE THREAD

**Issue by asseldonk** [linev/jsroot#28]
Hi,

when drawing a 2 dimensional graph with colz option and switching to 3d mode afterwards, the palette for the z-axis does not disappear:
![screen shot 2016-02-19 at 17 53 09](https://cloud.githubusercontent.com/assets/6368986/13182410/da614156-d731-11e5-945a-33a94bb9762f.png)

Best regards
Daniel

**Comment by linev** [comment]
Yes, I can confirm.  Fix is committed.

By chance hit other error with older Chrome.
Thanks for reporting the problem.

**Comment by linev** [comment]
I guess, problem is solved.
