### ISSUE TITLE
css class names

### ISSUE THREAD

**Issue by asseldonk** [linev/jsroot#29]
Hi,
there might occur a problem with the css class names you are using. Names like 'toolbar' are very commonly used names. When jsroot is integrated into a project which also use this class names, style information can be overwritten.
I made a screenshot of a jupyter-notebook, using jsroot. The upper toolbar of jupyter is repositioned after loading jsroot (first picture: jsroot disabled - everything is fine, second picture: after drawing with jsroot, the toolbar is moved up):
![screen shot 2016-02-22 at 00 48 42](https://cloud.githubusercontent.com/assets/6368986/13206483/148c1706-d8ff-11e5-8422-64c217ddd677.png)
![screen shot 2016-02-22 at 00 47 33](https://cloud.githubusercontent.com/assets/6368986/13206484/1dadd554-d8ff-11e5-883d-80ec23c46460.png)

There are two possible solutions:
- using unique names (e.g. giving every class the prefix jsroot) which is not very nice
- nesting

Nesting is very easy to realize with sass or less (furthermore, both are much easier to handle than css). I translated your css into sass and nested all classes in a superior jsroot class: f1da90beb0fab880c726fac3788cdfb30f58b793
The only thing left is adding the superior jsroot class to the html: 976ebc2b967a95aa09015443c95acb1ffc887eea
I didn't had the time to test everything in detail, but it seems to work.

Best regards
Daniel

P.S.: Sorry for writing all those issues

**Comment by asseldonk** [comment]
At the moment, I don't understand why nesting doesn't work for the tooltip of 3d graphs.
```css
.tt3d_border
  display     : block
  height      : 5px
  margin-left : 5px
  overflow    : hidden

.tt3d_cont
  display     : block
  padding     : 2px 12px 3px 7px
  margin-left : 5px
  font-size   : 11px
  background  : #777
  color       : #fff
```

**Comment by linev** [comment]
Hi,

I was expecting problem like this. And was too lazy to fix it, introducing more unique class identifier.

>There are two possible solutions:
>     - using unique names (e.g. giving every class the prefix jsroot) which is not very nice
>    - nesting

Thy you do not like "jsroot_" prefix? Such approach will be consistent and does not depend from HTML elements hierarchy. 

> At the moment, I don't understand why nesting doesn't work for the tooltip of 3d graphs.

This is just first from many potential problems when using nesting. 
Explanation is simple - tooltip element inserted directly to HTML document, not into  
<div id="simpleGUI" ... container. 

> Nesting is very easy to realize with sass or less

Means I need to write my stylesheets with sass language and then convert it into CSS with SASS scripts? Disadvantage of such approach - anybody who will try to modify styles, should care about correct compilation of stylesheets with SASS.

Could we agree on following solution:
- use nesting with top 'jsroot' class name
- but keep CSS files as they are - add .jsroot string 'by hand'
Could you provide such patch? 

> The only thing left is adding the superior jsroot class to the html
'jsroot' class name should be added in several places, I will care about this.

Regards,
Sergey

**Comment by asseldonk** [comment]
I like nesting because - in my mind - it is easier to read and maintain. Furthermore, I thought it would be less effort to change the css files than to go through all js files and change the selectors.

And I agree, the disadvantage of SASS is, everyone needs to care about the compilation. But the advantage are: it is faster to write, easier to read and to maintain and the code has more the structure of the html. When using editors like sublime or atom, you can automatically compile sass when saving the document. But you are right, everyone needs to care about the compilation.

I can provide you both, css with prefixed jsroot classes (e.g. jsroot-) or a nested version. As you prefer,

**Comment by asseldonk** [comment]
Oh, I see you already started. So I give you the nested version.

**Comment by linev** [comment]
> I like nesting because - in my mind - it is easier to read and maintain.
Probably yes, but I had problems to keep nested classes under control with jquery-ui.
For every new attribute they use another class and sometime they overwrite behavior of each other.

But lets try with nested classes.

**Comment by linev** [comment]
I fix several problems, but now nested classes should work.
I close this issue.

**Comment by asseldonk** [comment]
I just found some small thing left over: the helper for resizing a pad in flex layout does not work
https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.jquery.js#L906-921
with
https://github.com/linev/jsroot/blob/master/style/JSRootPainter.css#L61-63

**Comment by linev** [comment]
You are right.
I tried to fixed it - there were no "jsroot" top class in these layouts.
Could try again.
I just implementing resize of TFrame - not yet completely working.
