### ISSUE TITLE
Installation jsroot via bower

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#32]
Hi @linev,

Are you planing to put jsroot in bower?
```
bower install jsroot
```
Thanks

**Comment by linev** [comment]
Hi @mvala 

I personally never use bower.
Will you test it if I put something like [this](https://github.com/mrdoob/three.js/blob/master/bower.json) into repository?

Regards

**Comment by mvala** [comment]
@linev yes i will

**Comment by mvala** [comment]
I think you should follow http://bower.io/docs/creating-packages/

**Comment by linev** [comment]
Could you try now?

**Comment by linev** [comment]
I install package under 'jsroot' name.
But I used too simple versions (like v4.3), which are not recognized by bower.
Next release will do v4.4.0

**Comment by mvala** [comment]
ok. package is installed. I think it would be better if you put d3js, threejs, jquery, jquery-ui as dependecy

**Comment by linev** [comment]
> I think it would be better if you put d3js, threejs, jquery, jquery-ui as dependecy

Could you propose the solution?

Which works also without bower.
I just want to avoid situation that I need to install additional packages just to start working with jsroot.

**Comment by mvala** [comment]
Ok, i will think about it.

**Comment by mvala** [comment]
so you will need to add to bower.json
```
dependencies": {
    "jquery": "~<version>",
    "jquery-ui": "~<version>",
...
  }
```
and put these scripts to ignore list
```
"ignore": [
    "*.md",
    "/docs",
    "/files",
    "/LICENSE",
    "scripts/jquery.min.js",
    "scripts/jquery-ui.min.js",
....
   ],
```

and it should be it. I already tried. if i will load all these javascript in my html file, JSRootCore.js will reuse. I just removed some javascripts from jsroot and it is working fine

**Comment by linev** [comment]
I tried myself.
`[shell] bower install jsroot`
It download many different packages.
Now question - how to explain that JSROOT should use them?

**Comment by mvala** [comment]
I am preparing example for you. so we can continue solve path for these java scripts

**Comment by linev** [comment]
JSROOT supports require.js.
It should be possible to correctly configure modules names here:
https://github.com/linev/jsroot/blob/master/scripts/JSRootCore.js#L24-L49

**Comment by mvala** [comment]
i prepared simple project at https://github.com/mvala/jsroot-example

you simply do
```
npm start
```
and it will install everything and starts server at port 3000. All bower packages are located in public/vendor
As you can see in ```public/index.html``` i am loading all dependencies by hand and then JSROOT sees them as already loaded. So this is working fine.

Some JSROOT part is loaded online but it needs ```scripts``` and ```style``` directory inside ```public``` and not in ```public/vendor/jsroot```. So page as it is when you right click on axis to get menu it will try to load other scripts or styles from public directory. Probably we need to get path where JSRootCore.js is loaded and load other from there

**Comment by linev** [comment]
When I try "npm start", it complains about zmq package.
Could you check error output:

> alice-rsn-web@0.0.0-alpha.1 prestart /home/linev/git/jsroot-example
> npm install

> zmq@2.14.0 install /home/linev/git/jsroot-example/node_modules/zmq
> node-gyp rebuild

make: Entering directory '/home/linev/git/jsroot-example/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
zmq.target.mk:80: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory '/home/linev/git/jsroot-example/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.7-21-desktop
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/linev/git/jsroot-example/node_modules/zmq
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
 
> ws@0.4.32 install /home/linev/git/jsroot-example/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/linev/git/jsroot-example/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:82: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/linev/git/jsroot-example/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! Linux 3.16.7-21-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linev/git/jsroot-example/npm-debug.log

npm ERR! Linux 3.16.7-21-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! alice-rsn-web@0.0.0-alpha.1 prestart: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alice-rsn-web@0.0.0-alpha.1 prestart script 'npm install'.
npm ERR! This is most likely a problem with the alice-rsn-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls alice-rsn-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linev/git/jsroot-example/npm-debug.log
linev@depc294:~/git/jsroot-example> npm owner ls zmg
npm ERR! owner ls Couldn't get owner data zmg
npm ERR! Linux 3.16.7-21-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "zmg"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/zmg
npm ERR! 404 
npm ERR! 404 'zmg' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linev/git/jsroot-example/npm-debug.log

**Comment by mvala** [comment]
Sorry i forgot to remove zmq dependency. Please do ```git pull``` now

**Comment by linev** [comment]
There is still some problems - now alice-rsn-web package.

Additional error details:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

npm ERR! Linux 3.16.7-21-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! alice-rsn-web@0.0.0-alpha.1 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alice-rsn-web@0.0.0-alpha.1 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the alice-rsn-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls alice-rsn-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linev/git/jsroot-example/npm-debug.log

npm ERR! Linux 3.16.7-21-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! alice-rsn-web@0.0.0-alpha.1 prestart: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alice-rsn-web@0.0.0-alpha.1 prestart script 'npm install'.
npm ERR! This is most likely a problem with the alice-rsn-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls alice-rsn-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linev/git/jsroot-example/npm-debug.log

**Comment by mvala** [comment]
jsroot was taken from my git. I fixed it. i hope it will be fine

**Comment by linev** [comment]
Now it works for me.

Could you check how to correctly use require.js with bower?
I mean - somewhere should be extra js script, which includes all configured by bower packages.
Than one could skip all additional scripts includes and use in the code:

    require(['jsroot'], function(jsroot) {
         jsroot.NewHttpRequest("canvas_tf1.json", 'object', function(obj) {
            jsroot.draw("drawing", obj, "hist");
         }).send();
      });

I have standalone [example](http://jsroot.gsi.de/latest/demo/example_require.htm), but now we need to deal with bower and its management.

**Comment by mvala** [comment]
maybe this https://github.com/yeoman/bower-requirejs ?

**Comment by mvala** [comment]
or http://stackoverflow.com/questions/25487857/require-js-files-from-bower-components-by-saying-requirelibrary-possible

**Comment by linev** [comment]
Second variant is fully manual.
One creates config.js file based on directory structure, used by bower.
But any changes in bower config may lead to problems.

First approach looks much more promising.  Could you evaluate it?
I guess, config.js file is generated automatically. 
In this case in the code one should have:

<script type="text/javascript" src="path/require.js" data-main="path/config.js"></script>

Rest will be handled inside `require(['jsroot']) ` statement automatically. 

It is much better way, while jquery.js or especially three.js loaded only when needed in such case.

**Comment by mvala** [comment]
Let me try

**Comment by mvala** [comment]
i have now generated config.js
```
require.config({
  shim: {

  },
  paths: {
    bootstrap: "vendor/bootstrap/dist/js/bootstrap",
    d3: "vendor/d3/d3",
    jsroot: "vendor/jsroot/scripts/JSRootCore"
  },
  packages: [

  ]
});
```
ann i have no idea where to load it. Sorry i am not expert in this yet. :) Can you give me hint?

**Comment by linev** [comment]
Could you commit your changes?
I will try to adjust config file generation. 
I already provide link on example with usage of require.js: 
http://jsroot.gsi.de/latest/demo/example_require.htm
But config.js file is not yet complete.

**Comment by mvala** [comment]
done. But i would recommend you to remove node_modules and public/vendor.

**Comment by linev** [comment]
I will play little bit.
Looks promising.

**Comment by linev** [comment]
You could see changes in my version of example.

For the future I am not sure if we really need external dependency in bower.json.
JSROOT able to recognize loaded d3.js or jquery.js and will reuse them.
In all other cases one can use included version of these libraries.

Is it ok with you if I remove dependency from bower.json?

**Comment by linev** [comment]
> Is it ok with you if I remove dependency from bower.json?

To clarify - you always can include dependency in your project and use them.
And JSROOT just reuse them.

**Comment by mvala** [comment]
But dependency does not mean that these scripts will be loaded. Only when one do ```bower install jsroot``` it will install these packages. And loading them in web page is another story

**Comment by mvala** [comment]
I think we only need change in jsroot core script that other jsroot scripts from same base directory as jsroot core and that would be enough

**Comment by linev** [comment]
> But dependency does not mean that these scripts will be loaded. Only when one do bower install jsroot it will install these packages. And loading them in web page is another story

But this that I mean. You download many libraries which you do not use by default.

> I think we only need change in jsroot core script that other jsroot scripts from same base directory as jsroot core and that would be enough

One could implement special 'bower' mode in JSRootCore. I could recognize somehow that script loaded in bower environment and use d3 and jquery and rest from other locations. 

But why one should do this? 
Only if user wants to use some better/new library version? But this one should do anyway by hand.
Any other reasons?

**Comment by mvala** [comment]
I see your point. But there are some libraries needed by core of jsroot, like d3js, jquery and so. I understand that to load three library is overkill if you don't use it. 
At least these libraries should be as dependency in bower. From my point of view, why i like bower is that i don't have to care what dependencies i need to download.

I think it would be enough to set variable **dir** correctly at https://github.com/linev/jsroot/blob/master/scripts/JSRootCore.js#L10 . This can be retrieved from location of JSRootCore.js. Something like http://stackoverflow.com/questions/2161159/get-script-path . And i think this would not change default behavior.

**Comment by linev** [comment]
> At least these libraries should be as dependency in bower.
This that I meant in the beginning of our discussion.
Either JSROOT relies on bower installed packages (with proper dependencies) or
one includes proper versions of libraries (as it is done now).
Support of both variants are tricky - solution with require.js is not perfect.

I will try to provide solution you propose as well.
There will be special mode when loading JSRootCore.js, which forces to use bower-installed packages.

**Comment by linev** [comment]
I update JSROOT and jsroot-example

Should now work with and without require.js.
Also found (and fix) some problems concerning require.js usage.
Please try and let me know.

**Comment by mvala** [comment]
It is working as expected. Thanks a lot
