### ISSUE TITLE
User function when moving movse over bin

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#36]
Is it possible to execute own custom function when i move mouse over come bin. I would like to take some action on that bin, e.g. shop projection of some other histogram

**Comment by linev** [comment]
Hi Martin,

> Is it possible to execute own custom function when i move mouse over come bin
Not yet. But it could be implemented.
With new tooltip functionality I have full control how tooltips are handled.

But there is potential performance problem. 
If mouse cursor moves over histogram bins, special function called more or less for each mouse position.
If you will try to draw new histogram for each such movement, it will block interface or made it very slow and unusable.

I propose following.
I will provide callback of user function not immediately, but 0.5 sec after mouse movement stopped. This is about the moment when box with tooltip information appears.

That kind of information you would like to have in such callback?
   - bin number and bin content. 
   - I also can provide reference on histogram itself.
   - graphical coordinates of mouse
   - anything else?

**Comment by linev** [comment]
Hi Martin,

Please look on this example:
http://jsroot.gsi.de/dev/demo/example_tooltip.htm

Is it that you want? Do you need something more?
Should work for TH1 and TH2 classes.

**Comment by mvala** [comment]
Yes, this would be enough for me now. Thanks a lot.
I am thinking also that moving over different bins will trigger some analysis on cluster for specific bin and i will update page later. So i would not need this delay of 0.5 sec to be smaller(maybe 0.1sec)? What is your advice?

**Comment by linev** [comment]
There is second parameter in the function ConfigureUserTooltipCallback:
https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.js#L1859
Just set it to 0.

**Comment by mvala** [comment]
Very goof
