### ISSUE TITLE
How can i get following object from my js?

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#41]
I would like to get directly object from file. I tried
```
     var filename = "http://disk.saske.sk/mvala/RsnOutFolder.root";
     JSROOT.OpenFile(filename, function(file) {
        file.ReadObject("pt/data/results/norm[1.10,1.15]/fit_0[0.997,1.050]/hCorrBC;1", function(obj) {
           JSROOT.draw("drawing", obj, "colz");
        });
     });
```
But it didn't work. It worked to access it via
http://jsroot.gsi.de/dev/?file=http://disk.saske.sk/mvala/RsnOutFolder.root&item=pt/data/results/norm[1.10,1.15]/fit_0[0.997,1.050]/hCorrBC

**Comment by linev** [comment]
Hi Martin,

You cannot get sub-items of TFolder, using TFile interface of JSROOT.
In the provided file you only can directly access "pt/data/results" object.
There is JSROOT.HierarchyPainter class, which could help you.
This class is used to build files/objects browser in the JSROOT, but can be used without GUI elements.
It can explore all supported objects type (like TFolder or TTask) and access sub-elements.

         var h = new JSROOT.HierarchyPainter("example");
         var fname = "http://disk.saske.sk/mvala/RsnOutFolder.root";
         var itemname = "pt/data/results/norm[1.10,1.15]/fit_0[0.997,1.050]/hCorrBC";

         h.OpenRootFile(fname, function() {
            h.get(itemname, function(node, obj) {
                JSROOT.draw("drawing", obj);
            });
         });

Complete example is [here](http://jsroot.gsi.de/dev/demo/example_hh.htm).

You can open many files at once, but than your item name should include filename in the beginning. Like:

         var itemname = "RsnOutFolder.root/pt/data/results/norm[1.10,1.15]/fit_0[0.997,1.050]/hCorrBC";

This is also not (yet) documented feature of JSROOT, but interface remains stable longer than 1 year.

**Comment by mvala** [comment]
Wht is node in ```h.get(itemname, function(node, obj) {```?

**Comment by linev** [comment]
> Wht is node in h.get(itemname, function(node, obj) {?
It is internal hierarchy structure (created by HierarchyPainter) to store different object attributes.
You can ignore it. 
You can see such structure clearly, when working with THttpServer like here:

https://root.cern.ch/js/latest/httpserver.C/h.json

**Comment by mvala** [comment]
Working very good and thank you for explanation
