### ISSUE TITLE
Set fitOpt before histogram is drawn

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#42]
Befora i draw histogram i would like to do equivalent in js as in root ```gStyle->SetOptFit(1111);```
Can you give me hint how to do it?

**Comment by linev** [comment]
Try to add following code before calling draw function:

     JSROOT.gStyle.OptFit = 1111;

But it only will work for histograms, which do not have statbox inside list of functions.

**Comment by mvala** [comment]
Ok, it is working.

**Comment by mvala** [comment]
Is there a way to make stat box bigger (resize with mouse)?

**Comment by linev** [comment]
Yes, you can resize statbox with the mouse - on top-left and bottom-right corner.
You also can redefine values of JSROOT.gStyle.StatNDC variable. Default is:

         JSROOT.gStyle.StatNDC  = { fX1NDC: 0.78, fY1NDC: 0.75, fX2NDC: 0.98, fY2NDC: 0.91 }

**Comment by mvala** [comment]
Thanks a lot. I was doing it on bottom-left. :)

**Comment by mvala** [comment]
Can i define OptFit in ```JSROOT.HierarchyPainter``` so it would be default when i click on histogram?

**Comment by linev** [comment]
You can overwrite JSROOT.gStyle.StatNDC variable at any place once JSRootCore.js is loaded.
JSROOT.HierarchyPainter uses it by default. If you are using normal UI, you can provide "optfit" parameter in URL string:

http://jsroot.gsi.de/dev/?file=http://disk.saske.sk/mvala/RsnOutMgr.root&item=RsnMgr;1/input/1/3/10/fOutput/hSignal&optfit=1111

**Comment by mvala** [comment]
I see, thanks

**Comment by linev** [comment]
Just for info - JSROOT v5 one should use:

    JSROOT.gStyle.fOptFit = 1111;
