### ISSUE TITLE
Function in JSROOT.HierarchyPainter when user click on the object

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#43]
Is there callback function i can call when user clicks on object in tree?

**Comment by linev** [comment]
Are you build your custom UI or want to "extend" normal interface?

**Comment by mvala** [comment]
Basicly custom UI and i would like to use JSROOT.HierarchyPainter and do some action when user would click on some object

**Comment by linev** [comment]
If you build your custom UI, you can easily modify instance of the HierarchyPainter class. Just do:

    var h = new JSROOT.HierarchyPainter("example");
    h.old_click = h.tree_click;

    h.tree_click = function(node,place) {
       // do that ever you want
       var itemname = d3.select(node.parentNode).attr('item');
      console.log('click item', itemname);

        // call old function
        this.old_click(node, place);
    }

Click function called at different situations - when user click "plus/minus", "icon" or "item". 

You also can redefine display() function of the HierarchyPainter - 
than you can redefine action only when object should be displayed.

**Comment by mvala** [comment]
I see. It is very usefull. Thank you
