### ISSUE TITLE
Is there way to do hist->GetXAxis()->SetRangeUser()?

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#44]
Is there way to do hist->GetXAxis()->SetRangeUser()?

**Comment by mvala** [comment]
I mean i understand i can zoom, but what if one wants to show lower limit than it is drawn. And unzoom will not do it

**Comment by linev** [comment]
For the moment I ignore user ranges, specified in TAxis classes. 
In primary JSROOT code I had several conflicts with range, configured via TPad options.
Therefore now only range, specified in TPad is used. 

But you are right - if there is only histogram object, one can apply user range for zooming. 
Could be done in near future

**Comment by mvala** [comment]
Ok. So i leave this issue open

**Comment by mvala** [comment]
I have problem that some bins in histogram are not fully shown.
http://jsroot.gsi.de/dev/?file=http://disk.saske.sk/mvala/RsnOutFolder.root&item=ctj/data/results/norm[1.10,1.15]/fit_0[0.997,1.050]/hCorrBC

**Comment by linev** [comment]
Hi Martin,

I fixed problem with not-shown bins (also in master) and provide workaround to apply user range for histogram zooming.
Handling of user ranges more complicated in the ROOT, especially when several histograms drawn on the same canvas. Workaround I apply to master, in dev version I will try to introduce more solid solution, also for TH2 histograms

**Comment by mvala** [comment]
Is it possible to have menu SetRangeUser when i rightclick on one of axix(x or y)

**Comment by linev** [comment]
Now user ranges should be supported in dev:
http://jsroot.gsi.de/dev/?nobrowser&file=http://jsroot.gsi.de/files/hsum.root&item=c1;1

**Comment by mvala** [comment]
But how can i set range?

**Comment by linev** [comment]
> Is it possible to have menu SetRangeUser when i rightclick on one of axix(x or y)

This functionality I introducing right now - object-specific content menus.
I plan to add possibility to change line/fill attributes. 
I also can add input for first/last bin, but it only makes sense for superimposed histograms, 
while for the first histogram normal zooming is full equivalent of this.

**Comment by linev** [comment]
> But how can i set range?

In your ROOT code before you store histogram into the file.

**Comment by mvala** [comment]
I see. Thanks
