### ISSUE TITLE
Color transparency

### ISSUE THREAD

**Issue by chapleau** [linev/jsroot#45]
Hello,

I have a TMultiGraph with many graphs where each line's color is set using SetLineColorAlpha (prior saving everything into a ROOT file). 
When drawing in the ROOT console, I'd do:

```
root [1] gStyle->SetCanvasPreferGL(1);
root [2] mg->Draw("AL")
root [3] gROOT->GetListOfColors()->AddAll(mycolors) 
```

where "mycolors" is an array of user-defined colors. 
I managed to get all  this working (well, almost) in JSROOT using:

```
JSROOT.OpenFile(filename, function(file) {
             file.ReadObject("mycolors", function(obj) {
                  JSROOT.Painter.adoptRootColors(obj);
                  file.ReadObject("mg", function(obj_g) {
                      JSROOT.draw("object_draw", obj_g, "AL");
                   });
             });
         });
```

The only thing I'm missing is the transparency. 
Is there a way to recover the transparency in JSROOT?

Thanks !

**Comment by linev** [comment]
Hi,
Up to now transparency (alfa parameter) was not used in jsroot.
I could look that can be done.
Could you provide your ROOT file that I can test it?
Regards,
Sergey

**Comment by chapleau** [comment]
Hello,

thanks for the prompt response.

Here's a test file.

Best,
-bertrand

**Comment by chapleau** [comment]
Sorry, file attachment failed.
Here's a small Python script:

```
from ROOT import gROOT, TFile,TGraph, TMultiGraph, TColor
gROOT.SetBatch(True) 
import numpy as np


def setPalette(n=100):
  ## color palette ##

  s  = np.array([0.00, 0.34, 0.61, 0.84, 1.00])
  r   = np.array([0.00, 0.00, 0.87, 1.00, 0.51])
  g = np.array([0.00, 0.81, 1.00, 0.20, 0.00])
  b  = np.array([0.51, 1.00, 0.12, 0.00, 0.00])

  FI = TColor.CreateGradientColorTable(s.shape[0], s, r, g, b, n)

  return range(FI, n+FI)


f_root = TFile("transparency_test.root","RECREATE") 
 
colors = setPalette()

gr_1 = TGraph(10,np.arange(10,dtype=float), np.random.random(10))
gr_2 = TGraph(10,np.arange(10,dtype=float), np.random.random(10))

gr_1.SetLineWidth(5)
gr_2.SetLineWidth(5)

gr_1.SetLineColorAlpha(colors[10],0.5)
gr_2.SetLineColorAlpha(colors[70],0.5)

mg = TMultiGraph()
mg.Add(gr_1)
mg.Add(gr_2)
mg.Write("mg")
gROOT.GetListOfColors().Write("mycolors",1)

f_root.Close()
```

**Comment by linev** [comment]
I add support of transparency into master and dev branches. 

You can make handling of custom colors much easier, if you will use TCanvas
Just add these lines to your macro:

    can = TCanvas("c1", "title", 3);
    mg.Draw();
    can.Write("c1");

TCanvas automatically stores complete colors list, and you can display canvas directly:

http://jsroot.gsi.de/dev/?file=../files/transparency_test.root&item=c1;1

Regards,
Sergey

**Comment by chapleau** [comment]
Awesome, thanks for the quick response.
