### ISSUE TITLE
Getting list of object under some directory via JSROOT.HierarchyPainter

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#47]
Is there a way how do i get list of object in file's and its directory for example

file: http://disk.saske.sk/mvala/RsnOutFolder.root
directory: pt/mc

Can i get list (names) of objects?

**Comment by linev** [comment]
It is in HierarchyPainter.expand() method.
I will provide example tomorrow

**Comment by mvala** [comment]
Thanka

**Comment by linev** [comment]
This example shows working code for the latest release version:
https://jsfiddle.net/1xvxp4ca/3/
I will add some additional feature to dev version to make code simpler

**Comment by linev** [comment]
This variant works only with dev version:
https://jsfiddle.net/1xvxp4ca/4/
Now HierarchyPainter.expand() callback function directly returns correspondent hierarchy item

**Comment by linev** [comment]
Hi Martin,

I hope, you get that you want.
I close issue.

**Comment by mvala** [comment]
I didn't have time to try it yet. I will reopen in case of problems
