### ISSUE TITLE
When i zoom in is it possible to get new coordinates of the axis ?

### ISSUE THREAD

**Issue by NickKok** [linev/jsroot#48]
Hi linev,
![untitled](https://cloud.githubusercontent.com/assets/8222731/14522936/5a267c38-0231-11e6-9535-92735a58b917.png)

I have a TH2(which display the tracks and the energy of particles) and TH1(histogram of the data).
I want to implement a function that when someone zoom in the TH2 find the new coordinates of the axis and display the histogram of the zoom area only.

**Comment by linev** [comment]
I hope I understand you correctly.
If somebody zoom range on left TH2, zooming range automatically changes on right TH1.
You want it this way?

**Comment by NickKok** [comment]
Yes

**Comment by linev** [comment]
Very short answer - you can redefine Zoom function in hist painter, which you get as return value from JSROOT.draw().
I will prepare jsfiddle today later, demonstrating such possibility.

**Comment by NickKok** [comment]
OK thans a lot

**Comment by linev** [comment]
Here is example: https://jsfiddle.net/obj9vffj/

Main idea is to redefine Zoom/Unzoom function and call them from other painter:

      var h1painter, h2painter;
      file.ReadObject("hpx;1", function(obj) {
         h1painter = JSROOT.draw("drawth1", obj, "hist");
      });
      file.ReadObject("hpxpy;1", function(obj) {
         h2painter = JSROOT.draw("drawth2", obj, "col");
         h2painter.WhenReady(function() {
            h2painter.OldZoom = h2painter.Zoom;
            h2painter.Zoom = function(xmin,xmax,ymin,ymax) {
               h1painter.Zoom(xmin, xmax);
               this.OldZoom(xmin,xmax,ymin,ymax);
            }
            h2painter.OldUnzoom = h2painter.Unzoom;
            h2painter.Unzoom = function(dox,doy,doz) {
               if (dox) h1painter.Unzoom(dox);
               this.OldUnzoom(dox,doy,doz);
            }
         });
      });

**Comment by NickKok** [comment]
Thanks

**Comment by NickKok** [comment]
The Zoom function works perfect as i want it but when i unzoom the first the second remain with zoom and i can see that you have done and unzoom.

**Comment by linev** [comment]
Is it working for you on jsfiddle.net example?

**Comment by NickKok** [comment]
No

**Comment by linev** [comment]
As I can see now, it does not work when you press button,
but should work if you double click on the canvas or use context menu

**Comment by NickKok** [comment]
Yeah you are right.

**Comment by linev** [comment]
I update example - now it is:
https://jsfiddle.net/obj9vffj/2/

**Comment by linev** [comment]
And this is how it works with dev version:
https://jsfiddle.net/obj9vffj/3/
You can use mouse wheel for zooming

**Comment by NickKok** [comment]
Thanks I really appreciate your help

**Comment by linev** [comment]
I guess, I can close this issue

**Comment by linev** [comment]
Hi @NickKok,
I made small adjustment in dev version.
Now one only need to redefine Zoom function:
https://jsfiddle.net/obj9vffj/4/
This function also used in unzooming.
In next days I plan to release current dev as 4.5.0 version.

**Comment by NickKok** [comment]
Hi linev 
The i have adjust your code to zoom and unzoom at the region that i want and make the histogram of the spesifc block that i have zoom but i have problem when i zoom in a frame then unzoom and go to a new frame to zoom then the pages crash and with debuging there is a problem with this line
 h2painter.OldZoom = h2painter.Zoom;
if i put it on comment the page doesn't crash but the th2 histogram doesn't zoom in.


`h1painter=null;
graph1=CreateHistogram(Math.max.apply(Math, obj.clusters.px_e),obj,valuesofHistogram);//take the energy of json file
h1painter=JSROOT.redraw('histogram', graph1);//create the TH1 graph
        
var h2painter=null;
h2painter =  JSROOT.redraw('object_draw', histo, "colz");
        
h2painter.WhenReady(function() {
                
    h2painter.OldZoom = h2painter.Zoom;
    h2painter.Zoom = function(xmin,xmax,ymin,ymax) {
		var valuesofZoom=[];
		for(var i=0;i<Math.max.apply(Math, obj.clusters.px_e);i++ ){//for loop from 0- max energy value to create histogram(TH1)
			valuesofZoom[i]=0;//initializes the array    
		}
                      
		for(var j=0;j<obj.clusters.px_x.length;j++){
			if( ( obj.clusters.px_y[j]> ymin &&  obj.clusters.px_y[j]<= ymax) &&( obj.clusters.px_x[j]>=xmin && obj.clusters.px_x[j]<=xmax)){
                valuesofZoom[parseInt(obj.clusters.px_e[j])]+=1;//count the values of the zoomming area to create hist
			}  
		}
		graph2=CreateHistogram(Math.max.apply(Math, obj.clusters.px_e),obj,valuesofZoom);//call the function to create TH1 hist
		h1painter=JSROOT.redraw('histogram', graph2,'hist');
		h2painter.OldZoom(xmin,xmax,ymin,ymax);
    };
    h2painter.OldUnzoom = h2painter.Unzoom;
    h2painter.Unzoom = function(dox,doy,doz) {
        if (dox || (dox===undefined)){
            graph1=CreateHistogram(Math.max.apply(Math, obj.clusters.px_e),obj,valuesofHistogram);//create the unzooming hist
            h1painter=JSROOT.redraw('histogram', graph1);
        } 
        h2painter.OldUnzoom(dox,doy,doz);
    };
});`

**Comment by NickKok** [comment]
I just post it if you have an idea of problem(maybe it will be more obvious to you)  i don't want to bother you and spend time for my bug.

**Comment by linev** [comment]
If you want to update drawing, you could use painter object directly:
 
     h2painter.UpdateObject(histo); h2painter.RedrawPad();
     h1painter.UpdateObject(graph); h1painter.RedrawPad();

In principle, JSROOT.redraw() doing the same, but need to find appropriate painter in canvas list.

You should be aware, that arguments of Zoom() could be following:
   * xmin!==xmax - normal zooming into X range
   * xmin===xmax===0 - unzooming of X rnage
   * xmin===xmax===undefined - do nothing with X range

If you try to use xmin,xmax values, you should be aware about all these usecases.

> and with debuging there is a problem with this line
> h2painter.OldZoom = h2painter.Zoom;
> if i put it on comment the page doesn't crash but the th2 histogram doesn't zoom in.

Change of zooming function should be done only once. After redraw you still have same painter.
If you try to reassign function this way again, you will get endless recursion.

> I just post it if you have an idea of problem
I will try to help as long as I can.

Regards,
Sergey

**Comment by NickKok** [comment]
Thanks i will check it out.
