### ISSUE TITLE
Axis title and label sizes when drawing canvas

### ISSUE THREAD

**Issue by chapleau** [linev/jsroot#50]
Hello,

when drawing a Canvas, the axis title and labels properties (like size notably) do not seem to be taken into account. Is there a way to loop over the histograms in a TCanvas directly into the JS and set manually the axis title size ?

Thanks

**Comment by linev** [comment]
Hi @chapleau,

Which jsroot version you are using?

Axis title and labels are properties of the histogram, not a canvas.
In latest jsroot (4.5.0) you can change these parameters via context menu (when mouse cursor is over correspondent axis). And I see no problem changing size of axis labels or title, also when histogram drawn with the canvas.

**Comment by chapleau** [comment]
Hello,

I'm using the lastest version (https://root.cern.ch/js/latest/scripts/JSRootCore.min.js)

My problem is the following: I've a TCanvas with a couple of histograms for which I set the axis tite size. I dump the whole canvas into JSON through TBufferJSON and read the latter via JSROOT. And there (i.e on the web page), the axis title size is just the default 0.035 (even though it is saved as a property in the JSON). That's why I was asking if there's a way to enforce those axis properties in JSROOT (programmatically I mean).

**Comment by linev** [comment]
Could you provide your json file that I can reproduce the problem?

**Comment by chapleau** [comment]
Well, I was preparing a little example but just can't reproduce the problem !
Sorry for the noise, I'll close this.

**Comment by linev** [comment]
Most probably, problem was fixed in the latest 4.5.0 release.
