### ISSUE TITLE
Disable Access context menus icon

### ISSUE THREAD

**Issue by NickKok** [linev/jsroot#75]
Hello linev,

Because i didn't want the user to can modify the context i have disable the right click so now they can't use access context menu. But there is the button"?" below the canvas. Is there any way to disable this button and don't let a gap at btns_layer?

Best,
Nikolaos

**Comment by linev** [comment]
Hi Nikolas,

Normally one can disable all kinds of context menu writing in the code:

`JSROOT.gStyle.ContextMenu = false;`

But you are right - "?" button will remain even if context menu is disabled.
I will fix it soon.

Regards,
Sergey
