### ISSUE TITLE
Reading root files in the HTML5 filesystems

### ISSUE THREAD

**Issue by goiwai** [linev/jsroot#8]
I have noticed that JSROOT changed its interface in recent update. I write ROOT files in the HTML5 filesystem (with Chrome) at the end of the simulation and I then display the file on browser with JSROOT.

Along with a quick reading the section of "File API" at https://github.com/linev/jsroot/blob/master/docs/JSROOT.md, my code now looks like:

```
<script type="text/javascript" src="https://root.cern.ch/js/dev/scripts/JSRootCore.js"></script>

// url looks like: filesystem:http://localhost:5103/temporary/B5.root
var f = new JSROOT.TFile(url, function(file) {
});
```

... I got a message "Uncaught TypeError: JSROOT.TFile is not a function". I appreciate much if you could give me some advices or if there are some example for this case.

Go

**Comment by linev** [comment]
sorry, I am in vacations.
will be back on 17th of august


Von Samsung Mobile gesendet


-------- Ursprüngliche Nachricht --------
Von: Go Iwai
Datum:04.08.2015 07:25 (GMT+01:00)
An: linev/jsroot
Betreff: [jsroot] Reading root files in the HTML5 filesystems (#8)


I have noticed that JSROOT changed its interface in recent update. I write ROOT files in the HTML5 filesystem (with Chrome) at the end of the simulation and I then display the file on browser with JSROOT.

Along with a quick reading the section of "File API" at https://github.com/linev/jsroot/blob/master/docs/JSROOT.md, my code now looks like:

<script type="text/javascript" src="https://root.cern.ch/js/dev/scripts/JSRootCore.js"></script>

// url looks like: filesystem:http://localhost:5103/temporary/B5.root
var f = new JSROOT.TFile(url, function(file) {
});


... I got a message "Uncaught TypeError: JSROOT.TFile is not a function". I appreciate much if you could give me some advices or if there are some example for this case.

Go

**Comment by linev** [comment]
Dear Go,

Sorry for delay.
When you include JSRootCore.js on your HTML page, you also in URL parameters should
specify functionality you would like to load. Like:

    <script type="text/javascript" src="https://root.cern.ch/js/dev/scripts/JSRootCore.js?2d&io"></script>

Old fashion - use JSROOT.AssertPrerequisites() function with similar arguments. But I recommend first approach.

**Comment by linev** [comment]
Many JSROOT examples you could find on https://root.cern.ch/js/dev/demo/jslinks.htm
At the end there are several examples of JSROOT API usage. For you case it is:
https://root.cern.ch/js/dev/demo/example_file.htm

**Comment by goiwai** [comment]
Dear Sergey,

Sorry for not replying sooner and thank you for kindly helping me. I am now able to draw root objects with a `JSRootCore.js`. I am gradually understanding APIs along with https://root.cern.ch/js/dev/demo/example_file.htm and other examples. Again if I lost something for ROOTJS, let me post a question here. Thank you very much!

Best regards,
Go

**Comment by goiwai** [comment]
Sorry let me post one more question. Is there any possibility to draw root objects with not passing `load` parameter?

Here is what I want to do (but I can not do so far):

```
<head>
<script type="text/javascript" src="https://root.cern.ch/js/dev/scripts/JSRootCore.js?io&2d"></script>

<script type="text/javascript" charset="utf-8">
window.onload = function() {
    createGUI();
}

function createGUI() {
    var filename = "../../files/hsimple.root";
    new JSROOT.TFile(filename, function(file) {
        file.ReadObject("hpxpy;1", function(obj) {
            JSROOT.draw("drawing", obj, "colz");
        });
    });
}
</script>
</head>

<body><div id="drawing" style="width:100%"></div></body>
```

I can draw objects by passing the function name to load like: `JSRootCore.js?io&2d&load=createGUI`.

**Comment by linev** [comment]
Hi
You should use JSROOT.AssertPrerequisities function.
It can be called in any place like

    JSROOT.AssertPrerequisities("io;2d", CreateGui);

**Comment by goiwai** [comment]
Hi Sergey,

Thank you! I could call a function `createGUI()` with not passing load parameter to `JSRootCore.js`. The minimum code looks like:

```
<head>
<script type="text/javascript" src="https://root.cern.ch/js/dev/scripts/JSRootCore.js"></script>

<script type="text/javascript" charset="utf-8">
window.onload = function() {
    JSROOT.AssertPrerequisites("io;2d", createGUI);
}

function createGUI() {
    var filename = "../../files/hsimple.root";
    new JSROOT.TFile(filename, function(file) {
        file.ReadObject("hpxpy;1", function(obj) {
            JSROOT.draw("drawing", obj, "colz");
        });
    });
}
</script>
</head>

<body><div id="drawing" style="width:100%"></div></body>
```
