### ISSUE TITLE
Unable to draw branches of TTree

### ISSUE THREAD

**Issue by aminnj** [linev/jsroot#80]
With a local reproduction of something like [1], drawing a branch of a TTree displays nothing. In this case, I also tried allowing CORS (but not sure how this would help because in either case I can display histograms in a TFile just fine) with no luck. Similarly, the demo page in [1] is unable to display the drawn branches in both Chrome and Firefox on OSX (for example, right clicking on 'px' and choosing Draw does nothing).

[1] https://root.cern.ch/js/latest/api.htm#url_syntax_open_file

**Comment by linev** [comment]
Dear Nick,

At the moment any kind of TTree::Draw functionality is not supported in JSROOT.
One only can see list of branches in the TTree - but that's it.
In principle, I could try to implement very primitive use-cases (like histograming of values in single branch). But to be able to use full power of TTree::Draw(), I recommend to use THttpServer like:

https://root.cern.ch/js/latest/api.htm#httpserver_c_tree_player

**Comment by aminnj** [comment]
Great, I will look into that! Thanks!

**Comment by linev** [comment]
More info about THttpServer you will find here;

https://github.com/linev/jsroot/blob/master/docs/HttpServer.md

**Comment by linev** [comment]
Dear Nick,

I implement first draft of simplified TTree::Draw().
It only works for branches with single leaf (maximal split level) and only for basic data types.
Looks like this:

http://jsroot.gsi.de/dev/?file=../files/hsimple.root&item=ntuple;1/px

Can you try and let me know if it works for you.

Regards,
Sergey

**Comment by aminnj** [comment]
Hi Sergey,

That is a wonderful addition, thanks! I have one issue though. I am able to
draw those branches flawlessly on the link you provided. However, if I
untar the dev version and use the same root file, I get
http://uaf-6.t2.ucsd.edu/~namin/dump/jsroot/index.htm?file=files/hsimple.root
which does not let me draw the branches. My version still lets me draw
regular histograms, canvases, etc. Am I missing something?

Thanks again,
Nick

**Comment by linev** [comment]
Hi Nick,
You are using dev code from yesterday.
You should update it to the newest state.
Regards,
Sergey

**Comment by aminnj** [comment]
Hi Sergey,

Thanks for the pointer. If I check out the jsroot repository and switch to
the dev branch (23/08/16), I see:
http://uaf-6.t2.ucsd.edu/~namin/dump/jsroot/jsroot/index.htm?file=../files/WJets.root
Indeed I have the option to draw the branch, but at the bottom left I see
"draw 0%" even after waiting a while.

Nick

**Comment by linev** [comment]
I will check tomorrow.
It is still very preliminary code and I checked it only with TNtuple.

**Comment by linev** [comment]
Hi,

I fix this simple error - now it works with your tree too:

http://jsroot.gsi.de/dev/?file=../files/tmp/WJets.root&item=t;1/met

But it is relatively slow, while you have many small baskets in your branches.
This leads to many separate HTTP requests.
I will try to optimize this - I want to do this anyway.

Sergey

**Comment by linev** [comment]
Now reading of such trees should work faster.
I implement support of multi-range requests.
Now instead of ~200 requests only 2 are issued.

http://jsroot.gsi.de/dev/?file=../files/tmp/WJets.root&item=t;1/met

**Comment by aminnj** [comment]
This is great. Thanks for this!

**Comment by linev** [comment]
Finally TTree support introduced in JSROOT.
One can read mostly all kind of branches and use them in TTree::Draw expressions - 
all without involving real ROOT code.
Everything in new 5.0.0 version
