### ISSUE TITLE
 Gauss fitting in TH1

### ISSUE THREAD

**Issue by NickKok** [linev/jsroot#90]
Hello Linev,

In my application i create a TH1 histogram and i would like to make a gauss fitting as these examples:

https://root.cern.ch/js/latest/?nobrowser&file=../files/rf107.root&item=rf107_plotstyles;1&opt= 

But i can't see the code of this page. Could you give me a clue of how i can do it?

**Comment by linev** [comment]
Hi,

This is canvas, produced with macro from ROOT tutorials:
tutorials/roofit/rf107_plotstyles.C
Means fitting is done with normal RooFit code.
There is no fitting, implemented with JavaScript.

Regards,
Sergey

**Comment by NickKok** [comment]
OK, thanks a lot
