### ISSUE TITLE
Set bins in the TH1

### ISSUE THREAD

**Issue by NickKok** [linev/jsroot#93]
Hi Linev,

Is it possible to set the bins in the TH1. Example(10 bins from 10-100)

**Comment by linev** [comment]
Hi,

There is example which shows how histograms can be created and filled:
http://jsroot.gsi.de/dev/demo/example_tooltip.htm

More examples you can find here:
http://jsroot.gsi.de/dev/api.htm

Regards,
Sergey

**Comment by NickKok** [comment]
Is it possible to change the size of the bin?

The bin size is 1. I would like for example(the values of x from 0-10  will be in the same bin in the histogram in this case bin size is 10)

**Comment by linev** [comment]
Hi,

After you create histogram, just set:
`histo.fXaxis.fXmin = your_xmin; histo.fXaxis.fXmax = your_xmax;` 

Regards,
Sergey

**Comment by linev** [comment]
I hope problem is clarified and can be close.
